export const aktuality = [
  {
    id: 11,
    Nazev: 'PF 2020',
    Text: '<p>Vše nejlepší do nového roku přeje LMŠ Mariánka!</p>',
    created_at: '2021-03-11T21:36:39.252Z',
    updated_at: '2021-03-11T21:36:39.267Z',
    Datum: null,
    Image: {
      id: 30,
      name: 'pf2020.png',
      alternativeText: '',
      caption: '',
      width: 800,
      height: 348,
      formats: {
        small: {
          ext: '.png',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1615498596/small_pf2020_5397babb27.png',
          hash: 'small_pf2020_5397babb27',
          mime: 'image/png',
          name: 'small_pf2020.png',
          path: null,
          size: 39.04,
          width: 500,
          height: 218,
          provider_metadata: {
            public_id: 'small_pf2020_5397babb27',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.png',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1615498595/medium_pf2020_5397babb27.png',
          hash: 'medium_pf2020_5397babb27',
          mime: 'image/png',
          name: 'medium_pf2020.png',
          path: null,
          size: 78.64,
          width: 750,
          height: 326,
          provider_metadata: {
            public_id: 'medium_pf2020_5397babb27',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.png',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1615498594/thumbnail_pf2020_5397babb27.png',
          hash: 'thumbnail_pf2020_5397babb27',
          mime: 'image/png',
          name: 'thumbnail_pf2020.png',
          path: null,
          size: 12.61,
          width: 245,
          height: 107,
          provider_metadata: {
            public_id: 'thumbnail_pf2020_5397babb27',
            resource_type: 'image',
          },
        },
      },
      hash: 'pf2020_5397babb27',
      ext: '.png',
      mime: 'image/png',
      size: 76.66,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1615498593/pf2020_5397babb27.png',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'pf2020_5397babb27',
        resource_type: 'image',
      },
      created_at: '2021-03-11T21:36:36.342Z',
      updated_at: '2021-03-11T21:36:36.391Z',
    },
  },
  {
    id: 12,
    Nazev: 'Výtvarné dopoledne pro děti a rodiče',
    Text:
      '<p>Milí rodiče a děti,&nbsp;</p><p>zveme vás na zimní výtvarné dopoledne v přírodě. Vyzkoušejte s námi trochu toho bytí v usínající přírodě, která nám stále dává inspiraci, co dělat venku... Přihlašování je <a href="https://docs.google.com/forms/d/e/1FAIpQLSfd8_Ou0M5vxn9WqvgmM9PYY0jsTC6R8_gWxl0k09TleowpSw/viewform?usp=sf_link">tady</a>. Těší se na vás lektorka Klára Krchňavá a výtvarnice Zuzana Trnková.</p>',
    created_at: '2021-03-11T21:37:30.308Z',
    updated_at: '2021-03-11T21:37:30.320Z',
    Datum: null,
    Image: {
      id: 31,
      name: 'zvonecek_vytvarne.jpg',
      alternativeText: '',
      caption: '',
      width: 553,
      height: 800,
      formats: {
        small: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1615498647/small_zvonecek_vytvarne_d177050f2c.jpg',
          hash: 'small_zvonecek_vytvarne_d177050f2c',
          mime: 'image/jpeg',
          name: 'small_zvonecek_vytvarne.jpg',
          path: null,
          size: 50.58,
          width: 346,
          height: 500,
          provider_metadata: {
            public_id: 'small_zvonecek_vytvarne_d177050f2c',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1615498646/medium_zvonecek_vytvarne_d177050f2c.jpg',
          hash: 'medium_zvonecek_vytvarne_d177050f2c',
          mime: 'image/jpeg',
          name: 'medium_zvonecek_vytvarne.jpg',
          path: null,
          size: 103.24,
          width: 518,
          height: 750,
          provider_metadata: {
            public_id: 'medium_zvonecek_vytvarne_d177050f2c',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1615498646/thumbnail_zvonecek_vytvarne_d177050f2c.jpg',
          hash: 'thumbnail_zvonecek_vytvarne_d177050f2c',
          mime: 'image/jpeg',
          name: 'thumbnail_zvonecek_vytvarne.jpg',
          path: null,
          size: 6.13,
          width: 108,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_zvonecek_vytvarne_d177050f2c',
            resource_type: 'image',
          },
        },
      },
      hash: 'zvonecek_vytvarne_d177050f2c',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 119.7,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1615498645/zvonecek_vytvarne_d177050f2c.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'zvonecek_vytvarne_d177050f2c',
        resource_type: 'image',
      },
      created_at: '2021-03-11T21:37:28.033Z',
      updated_at: '2021-03-11T21:37:28.071Z',
    },
  },
  {
    id: 10,
    Nazev: 'Zápis na školní rok 2019/2020',
    Text:
      '<p>Milí rodiče a děti, zveme vás k zápisu do naší Lesní mateřské školy Mariánka!</p><p>Ředitelka LMŠ Mariánka vyhlašuje řádný zápis v termínu 7. 5. 2019 v čase 14:00 - 17:00. Rádi vás uvítáme i s vaším dítětem. S sebou si přineste:</p><ul><li>vyplněnou <a href="http://www.lesnimarianka.cz/Data/Sites/1/media/zadost_o_prijeti.docx">přihlášku s vyjádřením lékaře</a></li><li><a href="http://www.lesnimarianka.cz/Data/Sites/1/media/evidencni_list.docx">evidenční list</a></li><li><a href="http://www.lesnimarianka.cz/Data/Sites/1/media/dotazník.docx">dotazník</a></li><li>váš občanský průkaz</li><li>rodný list dítěte</li></ul><p>Formuláře je možné si stáhnout a vytisknout nebo vyzvednout ve školce v pátek 12.4. od 13 do 16 hodin.</p><p>Před zápisem se, prosím, seznamte s informacemi na webových stránkách, zejména v sekci Pro rodiče.&nbsp;Kritéria pro zápis jsou k přečtení v&nbsp;<a href="http://www.lesnimarianka.cz/Data/Sites/1/media/podminky_podavani_zadosti_o_prijeti.pdf">Podmínkách pro podávání žádosti o přijetí</a>.&nbsp;</p><p>LMŠ Mariánka přijímá děti, které prošly řádným očkováním&nbsp;(rodiče dodají potvrzení od lékaře nebo potvrzení o zdravotní kontraindikaci podle § 50 zák. č. 258/2000 Sb. o ochraně veřejného zdraví). Předškoláků se tato podmínka netýká.</p>',
    created_at: '2021-03-11T21:35:54.970Z',
    updated_at: '2021-03-11T21:35:54.983Z',
    Datum: null,
    Image: null,
  },
  {
    id: 13,
    Nazev: 'Jarní Zvoneček',
    Text:
      '<p>Přihlašovací formulář <a href="https://docs.google.com/forms/d/e/1FAIpQLSeaFQu_9xiJvqUEKK6Xk58Z_ylwIf2PFjxp5WD7HhioeL0Ipg/viewform?usp=sf_link">ZDE.</a></p>',
    created_at: '2021-03-11T21:38:27.498Z',
    updated_at: '2021-03-11T21:38:27.510Z',
    Datum: null,
    Image: {
      id: 32,
      name: 'zvonecek_jaro_2020.jpg',
      alternativeText: '',
      caption: '',
      width: 553,
      height: 800,
      formats: {
        small: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1615498697/small_zvonecek_jaro_2020_e62f975e13.jpg',
          hash: 'small_zvonecek_jaro_2020_e62f975e13',
          mime: 'image/jpeg',
          name: 'small_zvonecek_jaro_2020.jpg',
          path: null,
          size: 52,
          width: 346,
          height: 500,
          provider_metadata: {
            public_id: 'small_zvonecek_jaro_2020_e62f975e13',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1615498697/medium_zvonecek_jaro_2020_e62f975e13.jpg',
          hash: 'medium_zvonecek_jaro_2020_e62f975e13',
          mime: 'image/jpeg',
          name: 'medium_zvonecek_jaro_2020.jpg',
          path: null,
          size: 106.56,
          width: 518,
          height: 750,
          provider_metadata: {
            public_id: 'medium_zvonecek_jaro_2020_e62f975e13',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1615498696/thumbnail_zvonecek_jaro_2020_e62f975e13.jpg',
          hash: 'thumbnail_zvonecek_jaro_2020_e62f975e13',
          mime: 'image/jpeg',
          name: 'thumbnail_zvonecek_jaro_2020.jpg',
          path: null,
          size: 6.11,
          width: 108,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_zvonecek_jaro_2020_e62f975e13',
            resource_type: 'image',
          },
        },
      },
      hash: 'zvonecek_jaro_2020_e62f975e13',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 121.6,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1615498695/zvonecek_jaro_2020_e62f975e13.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'zvonecek_jaro_2020_e62f975e13',
        resource_type: 'image',
      },
      created_at: '2021-03-11T21:38:18.012Z',
      updated_at: '2021-03-11T21:38:18.053Z',
    },
  },
  {
    id: 14,
    Nazev: 'Uzavíráme do odvolání ',
    Text:
      '<p>UZAVÍRÁME DO ODVOLÁNÍ LMŠ Mariánka.</p><p>Na základě preventivních opatření vlády ČR a <a href="http://www.brno-stred.cz/uredni-deska/narizeni-statutarniho-mesta-brna-c-5-2020-o-prijeti">nařízení Rady města Brna č. 5/2020</a> uzavíráme do odvolání provoz LMŠ Mariánka s&nbsp;platností od 17.3.2020. Podporujeme a přidáváme se takto k&nbsp;preventivním krokům a snaze omezit kontakt mezi lidmi ve větší skupině navzájem. Nikdo z nás by si v budoucnu určitě neodpustil, kdybychom přispěli k nakažení kohokoliv z Vás nebo Vašich blízkých.</p><p>Přejeme Vám hodně sil a pevné zdraví!</p>',
    created_at: '2021-03-11T21:39:02.510Z',
    updated_at: '2021-03-11T21:39:02.519Z',
    Datum: null,
    Image: null,
  },
  {
    id: 15,
    Nazev: 'Zápis na školní rok 2020/2021',
    Text:
      '<p>Na základě <a href="http://www.msmt.cz/opatreni-k-zapisum-do-ms-pro-skolni-rok-2020-2021?fbclid=IwAR0tMCokMnvv4SUpiwHpUmrlopwJfojmtl45KnZecQ3WpEcOljs_GTGGbnA">opatření</a> MŠMT k&nbsp;organizaci zápisů k&nbsp;předškolnímu vzdělávání pro rok 2020/21 upravujeme zápis do LMŠ Mariánka pro letošní rok následovně:</p><p>Termín: 2. – 16. 5. 2020</p><p>Postup pro podání přihlášky:</p><p>1) stáhněte si žádost o přijetí, čestné prohlášení o očkování, evidenční list a dotazník v sekci O Mariánce/Dokumenty;&nbsp;</p><p>2) vyplněnou žádost (část Vyjádření lékaře vynechte), evidenční list, dotazník, čestné prohlášení o očkování + kopii očkovacího průkazu a kopii rodného listu dítěte nám můžete doručit v&nbsp;termínu 2. – 16. 5. 2020 následujícími způsoby:</p><ul><li>do datové schránky školy: 6h4qvbm,</li><li>e-mailem s uznávaným elektronickým podpisem (nelze jen poslat prostý email!) na adresu koordinator@lesnimarianka.cz,</li><li>poštou na adresu: LMŠ Mariánka, Viničné Šumice 137, 664 06 Viničné Šumice</li><li>osobně: 7. 5. 2020 od 14 - 16 h na zahradě LMŠ Mariánka v Brně-Líšni</li></ul><p>Zájemci o individuální vzdělávání vyplní také Oznámení o individuálním vzdělávání dítětě.</p><p>3) do 1. června 2020 dostanete rozhodnutí o přijetí</p><p>Před podáním přihlášky si prosím přečtěte podrobné informace k&nbsp;zápisu a přijímání do Mariánky, které najdete v&nbsp;samostatné záložce Zápis. Děkujeme!</p>',
    created_at: '2021-03-11T21:39:24.187Z',
    updated_at: '2021-03-11T21:39:24.197Z',
    Datum: null,
    Image: null,
  },
  {
    id: 16,
    Nazev: 'OTEVŘENO',
    Text:
      '<p>Mariánka opět otevírá svá vrátka! Sice v omezenéme režimu, ale od pondělí 27. dubna si děti mohou zase užívat zahradu i kamarády.</p>',
    created_at: '2021-03-11T21:40:14.345Z',
    updated_at: '2021-03-11T21:40:14.357Z',
    Datum: null,
    Image: {
      id: 33,
      name: 'mari_jiri.jpg',
      alternativeText: '',
      caption: '',
      width: 800,
      height: 600,
      formats: {
        small: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1615498811/small_mari_jiri_3a9cbdf799.jpg',
          hash: 'small_mari_jiri_3a9cbdf799',
          mime: 'image/jpeg',
          name: 'small_mari_jiri.jpg',
          path: null,
          size: 40.33,
          width: 500,
          height: 375,
          provider_metadata: {
            public_id: 'small_mari_jiri_3a9cbdf799',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1615498810/medium_mari_jiri_3a9cbdf799.jpg',
          hash: 'medium_mari_jiri_3a9cbdf799',
          mime: 'image/jpeg',
          name: 'medium_mari_jiri.jpg',
          path: null,
          size: 87.46,
          width: 750,
          height: 563,
          provider_metadata: {
            public_id: 'medium_mari_jiri_3a9cbdf799',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1615498809/thumbnail_mari_jiri_3a9cbdf799.jpg',
          hash: 'thumbnail_mari_jiri_3a9cbdf799',
          mime: 'image/jpeg',
          name: 'thumbnail_mari_jiri.jpg',
          path: null,
          size: 8.37,
          width: 208,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_mari_jiri_3a9cbdf799',
            resource_type: 'image',
          },
        },
      },
      hash: 'mari_jiri_3a9cbdf799',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 102.54,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1615498809/mari_jiri_3a9cbdf799.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'mari_jiri_3a9cbdf799',
        resource_type: 'image',
      },
      created_at: '2021-03-11T21:40:12.144Z',
      updated_at: '2021-03-11T21:40:12.181Z',
    },
  },
  {
    id: 17,
    Nazev: 'Letní tábory 2020',
    Text: '<p>Stromík a Mariánka vás zvou na letní příměstské tábory!</p>',
    created_at: '2021-03-11T21:41:31.477Z',
    updated_at: '2021-03-11T21:41:31.489Z',
    Datum: null,
    Image: {
      id: 35,
      name: 'tabory.jpg',
      alternativeText: '',
      caption: '',
      width: 504,
      height: 800,
      formats: {
        small: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1615498884/small_tabory_9c2da67823.jpg',
          hash: 'small_tabory_9c2da67823',
          mime: 'image/jpeg',
          name: 'small_tabory.jpg',
          path: null,
          size: 32.72,
          width: 315,
          height: 500,
          provider_metadata: {
            public_id: 'small_tabory_9c2da67823',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1615498883/medium_tabory_9c2da67823.jpg',
          hash: 'medium_tabory_9c2da67823',
          mime: 'image/jpeg',
          name: 'medium_tabory.jpg',
          path: null,
          size: 60.65,
          width: 473,
          height: 750,
          provider_metadata: {
            public_id: 'medium_tabory_9c2da67823',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1615498882/thumbnail_tabory_9c2da67823.jpg',
          hash: 'thumbnail_tabory_9c2da67823',
          mime: 'image/jpeg',
          name: 'thumbnail_tabory.jpg',
          path: null,
          size: 4.24,
          width: 98,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_tabory_9c2da67823',
            resource_type: 'image',
          },
        },
      },
      hash: 'tabory_9c2da67823',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 68.58,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1615498881/tabory_9c2da67823.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'tabory_9c2da67823',
        resource_type: 'image',
      },
      created_at: '2021-03-11T21:41:24.480Z',
      updated_at: '2021-03-11T21:41:24.525Z',
    },
  },
  {
    id: 18,
    Nazev: 'Podzimní Zvoneček',
    Text:
      '<p>Slyšíte jak něco cinká? To je Zvoneček, oblíbený kroužek pro děti s doprovodem. Začínáme už 30. září!&nbsp;</p><p>8 čtvrtečních dopolední můžete strávit v zahradě a blízkém lese, hrát si, tvořit, zpívat a radovat se společně se svými dětmi či vnoučaty z proměn podzimu.</p><p>Podrobnosti a přihlášku najdete&nbsp;<a href="https://docs.google.com/forms/d/e/1FAIpQLSeaFQu_9xiJvqUEKK6Xk58Z_ylwIf2PFjxp5WD7HhioeL0Ipg/viewform">zde</a>.</p>',
    created_at: '2021-03-11T21:42:18.459Z',
    updated_at: '2021-09-06T10:43:44.703Z',
    Datum: '6. 9.2021',
    Image: {
      id: 38,
      name: 'ZvonečekP2021.jpg',
      alternativeText: '',
      caption: '',
      width: 720,
      height: 1040,
      formats: {
        large: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1630924982/large_Zvonecek_P2021_a9ce6aba2e.jpg',
          hash: 'large_Zvonecek_P2021_a9ce6aba2e',
          mime: 'image/jpeg',
          name: 'large_ZvonečekP2021.jpg',
          path: null,
          size: 142.3,
          width: 692,
          height: 1000,
          provider_metadata: {
            public_id: 'large_Zvonecek_P2021_a9ce6aba2e',
            resource_type: 'image',
          },
        },
        small: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1630924983/small_Zvonecek_P2021_a9ce6aba2e.jpg',
          hash: 'small_Zvonecek_P2021_a9ce6aba2e',
          mime: 'image/jpeg',
          name: 'small_ZvonečekP2021.jpg',
          path: null,
          size: 47.89,
          width: 346,
          height: 500,
          provider_metadata: {
            public_id: 'small_Zvonecek_P2021_a9ce6aba2e',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1630924982/medium_Zvonecek_P2021_a9ce6aba2e.jpg',
          hash: 'medium_Zvonecek_P2021_a9ce6aba2e',
          mime: 'image/jpeg',
          name: 'medium_ZvonečekP2021.jpg',
          path: null,
          size: 93.63,
          width: 519,
          height: 750,
          provider_metadata: {
            public_id: 'medium_Zvonecek_P2021_a9ce6aba2e',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1630924981/thumbnail_Zvonecek_P2021_a9ce6aba2e.jpg',
          hash: 'thumbnail_Zvonecek_P2021_a9ce6aba2e',
          mime: 'image/jpeg',
          name: 'thumbnail_ZvonečekP2021.jpg',
          path: null,
          size: 6.41,
          width: 108,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_Zvonecek_P2021_a9ce6aba2e',
            resource_type: 'image',
          },
        },
      },
      hash: 'Zvonecek_P2021_a9ce6aba2e',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 147.23,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1630924980/Zvonecek_P2021_a9ce6aba2e.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'Zvonecek_P2021_a9ce6aba2e',
        resource_type: 'image',
      },
      created_at: '2021-09-06T10:43:03.952Z',
      updated_at: '2021-09-06T10:43:04.014Z',
    },
  },
  {
    id: 19,
    Nazev: 'Naše akce - venku a bezpečně',
    Text:
      '<p>Milí rodiče,</p><p>rádi bychom, abyste se i v&nbsp;této době cítili na našich aktivitách bezpečně a mohli si s&nbsp;námi užít plnými doušky podzimní přírody. Přečtěte si proto prosím pár následujících informací.</p><p>Většina našich programů se z&nbsp;principu koná venku, v&nbsp;prostředí lesa nebo zahrady. V&nbsp;zázemí Mariánky <strong>důsledně dodržujeme aktuální nařízení vlády a doporučení MŠMT </strong>pro zajištění bezpečné výuky – jsou zavedena režimová opatření v&nbsp;programu školky a zpřísněna hygienická a úklidová pravidla.</p><p>Totéž platí pro <strong>kroužky</strong> a aktivity, které v&nbsp;zázemí pořádá náš zřizovatel, spolek Kavyl.</p><p>Pokud nebude možné pořádat žádné vzdělávací akce z důvodu mimořádných opatření vlády či Ministerstva zdravotnictví, v předškolním vzdělávání zavedeme distanční výuku a u jednorázových akcí&nbsp;<strong>posuneme termín</strong>&nbsp;jejich konání.</p><p>U kroužků, které probíhají v&nbsp;pololetních cyklech, nabídneme náhradní termíny na všechny lekce, které nemohly proběhnout, v&nbsp;době, kdy nám to opatření umožní. Nebude-li to možné, vrátíme peníze za zrušené lekce.</p><p>Nebudete-li se moci našich aktivit zúčastnit z důvodů karantény či nemoci, můžete za sebe poslat náhradníka. Stačí nás o tom předem informovat.</p><p>V případě, že bude seminář či jiná jednorázová akce zrušena z naší strany (např. karanténa či rozhodnutí lektora), vrátíme vám zaplacený účastnický poplatek celý.</p><p><strong>Děkujeme za vaši přízeň a těšíme se na vás i vaše děti!</strong></p>',
    created_at: '2021-03-11T21:42:34.941Z',
    updated_at: '2021-03-11T21:42:34.950Z',
    Datum: null,
    Image: null,
  },
  {
    id: 20,
    Nazev: 'Letní tábory 2021',
    Text:
      '<p>Srdečně zveme na letní příměstské tábory u nás v Mariánce a v pozořickém Stromíku!</p><p>12. – 16. 7.:</p><p>Mariánka: S pohádkou v lese – předškolní děti 3–7 let</p><p>Stromík: Po stopách rudého bizona – předškolní děti 3–7 let</p><p>19. – 23. 7.:</p><p>Mariánka: Malý stopař – předškolní děti 3–7 let</p><p>Mariánka: Lesní olympiáda – školní děti 7–11 let</p><p>Stromík: Zázraky přírody – děti ve věku 5–8 let</p><p>26. – 30. 7.:&nbsp;</p><p>Stromík: Hurá do lesa – předškolní děti 3–7 let</p><p>Stromík: Hurá do lesa – školní děti 7–11 let</p><p>16. – 20. 8.:</p><p>Stromík: Kdo tam bydlí? – předškolní děti 3–7 let</p><p>Stromík: Kdo tam bydlí? – školní děti 7–11 let</p><p>Cena tábora je 1 900 Kč.</p><p>Podrobné informace najdete&nbsp;<a href="https://www.lesnikavyl.cz/files/tabory_2021_anotace.pdf">zde</a>.</p><p>Přihlásit se pak můžete online: <a href="https://docs.google.com/forms/d/e/1FAIpQLSfcZZDo1NSlXCrQ6HfZwXHuLV9p3xkmT7a9jrfmf4n564FzrA/viewform">PŘIHLÁŠKA</a></p>',
    created_at: '2021-03-11T21:43:12.180Z',
    updated_at: '2021-03-11T21:56:53.013Z',
    Datum: null,
    Image: {
      id: 34,
      name: 'tábory-2021-page-001.jpg',
      alternativeText: '',
      caption: '',
      width: 565,
      height: 800,
      formats: {
        small: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1615498874/small_tabory_2021_page_001_985c70f48d.jpg',
          hash: 'small_tabory_2021_page_001_985c70f48d',
          mime: 'image/jpeg',
          name: 'small_tábory-2021-page-001.jpg',
          path: null,
          size: 26.59,
          width: 353,
          height: 500,
          provider_metadata: {
            public_id: 'small_tabory_2021_page_001_985c70f48d',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1615498874/medium_tabory_2021_page_001_985c70f48d.jpg',
          hash: 'medium_tabory_2021_page_001_985c70f48d',
          mime: 'image/jpeg',
          name: 'medium_tábory-2021-page-001.jpg',
          path: null,
          size: 51.45,
          width: 530,
          height: 750,
          provider_metadata: {
            public_id: 'medium_tabory_2021_page_001_985c70f48d',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1615498873/thumbnail_tabory_2021_page_001_985c70f48d.jpg',
          hash: 'thumbnail_tabory_2021_page_001_985c70f48d',
          mime: 'image/jpeg',
          name: 'thumbnail_tábory-2021-page-001.jpg',
          path: null,
          size: 3.8,
          width: 110,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_tabory_2021_page_001_985c70f48d',
            resource_type: 'image',
          },
        },
      },
      hash: 'tabory_2021_page_001_985c70f48d',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 59.55,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1615498872/tabory_2021_page_001_985c70f48d.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'tabory_2021_page_001_985c70f48d',
        resource_type: 'image',
      },
      created_at: '2021-03-11T21:41:15.613Z',
      updated_at: '2021-03-11T21:41:15.648Z',
    },
  },
  {
    id: 22,
    Nazev: 'Zápis na školní rok 2021/22',
    Text:
      '<h3>Srdečně zveme k zápisu do naší Mariánky!</h3><p>Současná situace ovlivňuje organizaci zápisů pro letošní rok, kterou na základě opatření MŠMT upravujeme následovně:<br><br>Termín: <strong>2. – 16. 5. 2021</strong><br><br>Postup pro podání přihlášky:</p><p>1. stáhněte si Žádost o přijetí a Dotazník v záložce <a href="/onas/dokumenty">Dokumenty</a></p><p>2. vyplněnou žádost, dotazník a kopii rodného listu nám můžete doručit v termínu 2. – 16. 5. 2021 následujícími způsoby:</p><ul><li>do datové schránky školy: 6h4qvbm</li><li>e-mailem s uznávaným elektronickým podpisem (nelze jen poslat prostý email!) na adresu <a href="mailto:koordinator@lesnimarianka.cz">koordinator@lesnimarianka.cz</a></li><li>poštou na adresu: LMŠ Mariánka, Viničné Šumice 137, 664 06 Viničné Šumice</li><li>osobně: 11. 5. 2021 od 14 - 16 h na zahradě LMŠ Mariánka v Brně-Líšni</li></ul><p>Zájemci o individuální vzdělávání vyplní také <a href="/files/oznameni-iv.pdf">Oznámení o individuálním vzdělávání dítětě</a>.<br><br>3. do 1. června 2021 dostanete rozhodnutí o přijetí</p><p>Před podáním přihlášky si prosím přečtěte podrobné informace k zápisu a přijímání do Mariánky, které najdete v samostatné záložce <a href="/info/zapis">Zápis</a>.&nbsp;</p><p>Děkujeme a těšíme se na vaše děti!<br>&nbsp;</p>',
    created_at: '2021-03-26T16:35:23.789Z',
    updated_at: '2021-03-26T16:39:04.560Z',
    Datum: null,
    Image: null,
  },
  {
    id: 23,
    Nazev: 'Zvoneček jaro 2021',
    Text:
      '<p>Zvoneček otvírá svá vrátka! Už se moc těšíme, jak si vynahradíme podzimní hrátky, které jsme museli odložit na jaro!</p><p>Pro nováčky proto tentokrát máme jen poslední volná místa. Informace a přihlášku najdete v záložce <a href="/kavyl/krouzky">Aktivity Kavylu</a>.&nbsp;</p><p>Děkujeme za pochopení.</p>',
    created_at: '2021-05-19T09:05:35.105Z',
    updated_at: '2021-05-19T09:05:35.119Z',
    Datum: null,
    Image: {
      id: 37,
      name: 'AKCE PRO VEREJNOST.JPG',
      alternativeText: '',
      caption: '',
      width: 6000,
      height: 4000,
      formats: {
        large: {
          ext: '.JPG',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1621415126/large_AKCE_PRO_VEREJNOST_18026aeb12.jpg',
          hash: 'large_AKCE_PRO_VEREJNOST_18026aeb12',
          mime: 'image/jpeg',
          name: 'large_AKCE PRO VEREJNOST.JPG',
          path: null,
          size: 111.99,
          width: 1000,
          height: 667,
          provider_metadata: {
            public_id: 'large_AKCE_PRO_VEREJNOST_18026aeb12',
            resource_type: 'image',
          },
        },
        small: {
          ext: '.JPG',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1621415128/small_AKCE_PRO_VEREJNOST_18026aeb12.jpg',
          hash: 'small_AKCE_PRO_VEREJNOST_18026aeb12',
          mime: 'image/jpeg',
          name: 'small_AKCE PRO VEREJNOST.JPG',
          path: null,
          size: 37.34,
          width: 500,
          height: 333,
          provider_metadata: {
            public_id: 'small_AKCE_PRO_VEREJNOST_18026aeb12',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.JPG',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1621415126/medium_AKCE_PRO_VEREJNOST_18026aeb12.jpg',
          hash: 'medium_AKCE_PRO_VEREJNOST_18026aeb12',
          mime: 'image/jpeg',
          name: 'medium_AKCE PRO VEREJNOST.JPG',
          path: null,
          size: 70.5,
          width: 750,
          height: 500,
          provider_metadata: {
            public_id: 'medium_AKCE_PRO_VEREJNOST_18026aeb12',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.JPG',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1621415124/thumbnail_AKCE_PRO_VEREJNOST_18026aeb12.jpg',
          hash: 'thumbnail_AKCE_PRO_VEREJNOST_18026aeb12',
          mime: 'image/jpeg',
          name: 'thumbnail_AKCE PRO VEREJNOST.JPG',
          path: null,
          size: 11.09,
          width: 234,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_AKCE_PRO_VEREJNOST_18026aeb12',
            resource_type: 'image',
          },
        },
      },
      hash: 'AKCE_PRO_VEREJNOST_18026aeb12',
      ext: '.JPG',
      mime: 'image/jpeg',
      size: 1885.04,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1621415123/AKCE_PRO_VEREJNOST_18026aeb12.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'AKCE_PRO_VEREJNOST_18026aeb12',
        resource_type: 'image',
      },
      created_at: '2021-05-19T09:05:29.234Z',
      updated_at: '2021-05-19T09:05:29.269Z',
    },
  },
  {
    id: 27,
    Nazev: 'Adventní lesní stezka',
    Text:
      '<p>Chcete dětem přiblížit vánoční příběh a užít si procházku lesem? Připravili jsme pro vás adventní lesní stezku, která začíná u našich vrátek.</p><p>Přejeme krásné vánoční dny, plné rodinné pospolitosti a zdraví!</p>',
    created_at: '2021-12-20T07:59:35.651Z',
    updated_at: '2021-12-20T07:59:35.662Z',
    Datum: null,
    Image: {
      id: 41,
      name: 'adventni_stezka_2021.jpg',
      alternativeText: '',
      caption: '',
      width: 1654,
      height: 2339,
      formats: {
        large: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1639987160/large_adventni_stezka_2021_0ffec2517f.jpg',
          hash: 'large_adventni_stezka_2021_0ffec2517f',
          mime: 'image/jpeg',
          name: 'large_adventni_stezka_2021.jpg',
          path: null,
          size: 178.65,
          width: 707,
          height: 1000,
          provider_metadata: {
            public_id: 'large_adventni_stezka_2021_0ffec2517f',
            resource_type: 'image',
          },
        },
        small: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1639987162/small_adventni_stezka_2021_0ffec2517f.jpg',
          hash: 'small_adventni_stezka_2021_0ffec2517f',
          mime: 'image/jpeg',
          name: 'small_adventni_stezka_2021.jpg',
          path: null,
          size: 60.12,
          width: 354,
          height: 500,
          provider_metadata: {
            public_id: 'small_adventni_stezka_2021_0ffec2517f',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1639987161/medium_adventni_stezka_2021_0ffec2517f.jpg',
          hash: 'medium_adventni_stezka_2021_0ffec2517f',
          mime: 'image/jpeg',
          name: 'medium_adventni_stezka_2021.jpg',
          path: null,
          size: 116.48,
          width: 530,
          height: 750,
          provider_metadata: {
            public_id: 'medium_adventni_stezka_2021_0ffec2517f',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1639987159/thumbnail_adventni_stezka_2021_0ffec2517f.jpg',
          hash: 'thumbnail_adventni_stezka_2021_0ffec2517f',
          mime: 'image/jpeg',
          name: 'thumbnail_adventni_stezka_2021.jpg',
          path: null,
          size: 6.96,
          width: 110,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_adventni_stezka_2021_0ffec2517f',
            resource_type: 'image',
          },
        },
      },
      hash: 'adventni_stezka_2021_0ffec2517f',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 611.83,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1639987158/adventni_stezka_2021_0ffec2517f.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'adventni_stezka_2021_0ffec2517f',
        resource_type: 'image',
      },
      created_at: '2021-12-20T07:59:22.456Z',
      updated_at: '2021-12-20T07:59:22.489Z',
    },
  },
  {
    id: 24,
    Nazev: 'Podzimní Zvoneček',
    Text:
      '<p>Slyšíte jak něco cinká? To je Zvoneček, oblíbený kroužek pro děti s doprovodem. Začínáme už 30. září!&nbsp;</p><p>Podrobnosti a přihlášku najdete&nbsp;<a href="https://docs.google.com/forms/d/e/1FAIpQLSeaFQu_9xiJvqUEKK6Xk58Z_ylwIf2PFjxp5WD7HhioeL0Ipg/viewform">zde</a>.</p><p>Osm čtvrtečních dopolední můžete strávit v zahradě a blízkém lese, hrát si, tvořit, zpívat a radovat se společně se svými dětmi či vnoučaty z proměn podzimu.</p><p>&nbsp;</p>',
    created_at: '2021-09-06T10:44:39.908Z',
    updated_at: '2021-09-08T15:04:03.727Z',
    Datum: null,
    Image: {
      id: 39,
      name: 'ZvonečekP2021.jpg',
      alternativeText: '',
      caption: '',
      width: 720,
      height: 1040,
      formats: {
        large: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1630925072/large_Zvonecek_P2021_1d43c5deb5.jpg',
          hash: 'large_Zvonecek_P2021_1d43c5deb5',
          mime: 'image/jpeg',
          name: 'large_ZvonečekP2021.jpg',
          path: null,
          size: 142.3,
          width: 692,
          height: 1000,
          provider_metadata: {
            public_id: 'large_Zvonecek_P2021_1d43c5deb5',
            resource_type: 'image',
          },
        },
        small: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1630925073/small_Zvonecek_P2021_1d43c5deb5.jpg',
          hash: 'small_Zvonecek_P2021_1d43c5deb5',
          mime: 'image/jpeg',
          name: 'small_ZvonečekP2021.jpg',
          path: null,
          size: 47.89,
          width: 346,
          height: 500,
          provider_metadata: {
            public_id: 'small_Zvonecek_P2021_1d43c5deb5',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1630925073/medium_Zvonecek_P2021_1d43c5deb5.jpg',
          hash: 'medium_Zvonecek_P2021_1d43c5deb5',
          mime: 'image/jpeg',
          name: 'medium_ZvonečekP2021.jpg',
          path: null,
          size: 93.63,
          width: 519,
          height: 750,
          provider_metadata: {
            public_id: 'medium_Zvonecek_P2021_1d43c5deb5',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1630925071/thumbnail_Zvonecek_P2021_1d43c5deb5.jpg',
          hash: 'thumbnail_Zvonecek_P2021_1d43c5deb5',
          mime: 'image/jpeg',
          name: 'thumbnail_ZvonečekP2021.jpg',
          path: null,
          size: 6.41,
          width: 108,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_Zvonecek_P2021_1d43c5deb5',
            resource_type: 'image',
          },
        },
      },
      hash: 'Zvonecek_P2021_1d43c5deb5',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 147.23,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1630925070/Zvonecek_P2021_1d43c5deb5.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'Zvonecek_P2021_1d43c5deb5',
        resource_type: 'image',
      },
      created_at: '2021-09-06T10:44:34.206Z',
      updated_at: '2021-09-06T10:44:34.235Z',
    },
  },
  {
    id: 26,
    Nazev: 'Zvoneček - zima 2022',
    Text:
      '<p>Pro velký zájem otevíráme i zimní cyklus oblíbeného kroužku! Setkávat se budeme opět ve čtvrtky dopoledne od 13. 1. – 17. 2.</p><p>Přihlašovat se můžete <a href="https://docs.google.com/forms/d/e/1FAIpQLSeaFQu_9xiJvqUEKK6Xk58Z_ylwIf2PFjxp5WD7HhioeL0Ipg/viewform">zde</a>.</p>',
    created_at: '2021-12-20T07:56:24.288Z',
    updated_at: '2021-12-20T07:56:24.300Z',
    Datum: null,
    Image: null,
  },
  {
    id: 30,
    Nazev: 'Zvoneček jaro 2022',
    Text:
      '<p>Srdečně zveme na jarní cyklus Zvonečku!</p><p>Pro velký zájem otevíráme dvě skupiny:</p><p>čtvrtky: 7. 4., 14. 4., 21. 4., 28. 4., 5. 5., 12. 5., 19. 5., 26. 5.</p><p>pátky: 1. 4., 8. 4., 22. 4., 29. 4., 6. 5., 13. 5., 20. 5., 27. 5.</p><p>Scházet se budeme od 9:30 do 11:30 na zahradě LMŠ Mariánka.</p><p>Přihlašovat se můžete <a href="https://docs.google.com/forms/d/e/1FAIpQLSf1Y6EweGSEb30fGYOwp6K-fcu-tM7559jFa6d7FYqS4d7gtg/viewform?usp=sf_link">zde</a>.</p>',
    created_at: '2022-03-28T10:34:06.077Z',
    updated_at: '2022-03-28T10:34:06.133Z',
    Datum: null,
    Image: null,
  },
  {
    id: 29,
    Nazev: 'Tábory 2022',
    Text:
      '<p>Také už se nemůžete dočkat léta a vaše děti prázdninových dobrodružství?&nbsp;</p><p>Srdečně zveme na naše příměstské tábory!</p><p>Podrobnosti najdete <a href="https://lesnikavyl.cz/tabory">zde</a>.</p><p><a href="https://docs.google.com/forms/d/e/1FAIpQLScWgFfYAO-Kq2kIQYBE_HkwfMyVLR5uMBIzB7TAHu0clYbmEA/viewform">Přihlašovat se můžete online</a>.</p><p>&nbsp;</p>',
    created_at: '2022-03-14T15:17:03.436Z',
    updated_at: '2022-03-14T15:17:03.450Z',
    Datum: null,
    Image: {
      id: 43,
      name: 'tabory22_brcal_fb_ctvrty nastrel.JPG',
      alternativeText: '',
      caption: '',
      width: 2480,
      height: 3819,
      formats: {
        large: {
          ext: '.JPG',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1647271015/large_tabory22_brcal_fb_ctvrty_nastrel_b1f887da01.jpg',
          hash: 'large_tabory22_brcal_fb_ctvrty_nastrel_b1f887da01',
          mime: 'image/jpeg',
          name: 'large_tabory22_brcal_fb_ctvrty nastrel.JPG',
          path: null,
          size: 115.65,
          width: 649,
          height: 1000,
          provider_metadata: {
            public_id: 'large_tabory22_brcal_fb_ctvrty_nastrel_b1f887da01',
            resource_type: 'image',
          },
        },
        small: {
          ext: '.JPG',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1647271017/small_tabory22_brcal_fb_ctvrty_nastrel_b1f887da01.jpg',
          hash: 'small_tabory22_brcal_fb_ctvrty_nastrel_b1f887da01',
          mime: 'image/jpeg',
          name: 'small_tabory22_brcal_fb_ctvrty nastrel.JPG',
          path: null,
          size: 41.1,
          width: 325,
          height: 500,
          provider_metadata: {
            public_id: 'small_tabory22_brcal_fb_ctvrty_nastrel_b1f887da01',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.JPG',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1647271016/medium_tabory22_brcal_fb_ctvrty_nastrel_b1f887da01.jpg',
          hash: 'medium_tabory22_brcal_fb_ctvrty_nastrel_b1f887da01',
          mime: 'image/jpeg',
          name: 'medium_tabory22_brcal_fb_ctvrty nastrel.JPG',
          path: null,
          size: 74.73,
          width: 487,
          height: 750,
          provider_metadata: {
            public_id: 'medium_tabory22_brcal_fb_ctvrty_nastrel_b1f887da01',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.JPG',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1647271014/thumbnail_tabory22_brcal_fb_ctvrty_nastrel_b1f887da01.jpg',
          hash: 'thumbnail_tabory22_brcal_fb_ctvrty_nastrel_b1f887da01',
          mime: 'image/jpeg',
          name: 'thumbnail_tabory22_brcal_fb_ctvrty nastrel.JPG',
          path: null,
          size: 5.99,
          width: 101,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_tabory22_brcal_fb_ctvrty_nastrel_b1f887da01',
            resource_type: 'image',
          },
        },
      },
      hash: 'tabory22_brcal_fb_ctvrty_nastrel_b1f887da01',
      ext: '.JPG',
      mime: 'image/jpeg',
      size: 840.51,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1647271013/tabory22_brcal_fb_ctvrty_nastrel_b1f887da01.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'tabory22_brcal_fb_ctvrty_nastrel_b1f887da01',
        resource_type: 'image',
      },
      created_at: '2022-03-14T15:16:57.607Z',
      updated_at: '2022-03-14T15:16:57.648Z',
    },
  },
  {
    id: 32,
    Nazev: 'Den otevřených vrátek 2022',
    Text:
      '<p>Přijďte s námi oslavit Mezinárodní den lesních školek!</p><p><strong>3. května od 15 do 17 hodin&nbsp;</strong></p><p>V tento čas pro vás budou otevřená vrátka naší zahrady plné lákadel a tajemných koutů! Uvidíte, jak se žije v lesní školce, můžete se poptat na to, co vás zajímá.</p><p>Těšíme se na víděnou!</p>',
    created_at: '2022-04-07T08:15:07.807Z',
    updated_at: '2022-04-07T08:15:07.812Z',
    Datum: null,
    Image: null,
  },
  {
    id: 33,
    Nazev: 'Výsledky zápisu 2022/23',
    Text:
      '<figure class="table"><table><tbody><tr><td>číslo přihlášky</td><td>rozhodnutí</td><td>pořadí</td></tr><tr><td>2212</td><td>přijat</td><td>1</td></tr><tr><td>2211</td><td>přijat</td><td>2</td></tr><tr><td>2208</td><td>přijat</td><td>3</td></tr><tr><td>2207</td><td>přijat</td><td>4</td></tr><tr><td>2205</td><td>přijat</td><td>5</td></tr><tr><td>2210</td><td>přijat</td><td>6</td></tr><tr><td>2209</td><td>přijat</td><td>7</td></tr><tr><td>2202</td><td>přijat - nenastoupí</td><td>8</td></tr><tr><td>2204</td><td>přijat</td><td>9</td></tr><tr><td>2201</td><td>nepřijat</td><td>10</td></tr><tr><td>2203</td><td>nepřijat</td><td>11</td></tr><tr><td>2206</td><td>nepřijat</td><td>12</td></tr></tbody></table></figure>',
    created_at: '2022-06-02T06:33:21.256Z',
    updated_at: '2022-06-02T06:33:21.268Z',
    Datum: null,
    Image: null,
  },
  {
    id: 31,
    Nazev: 'Zápis na školní rok 2022/23',
    Text:
      '<p>Srdečně zveme k zápisu do Mariánky!</p><p>Den otevřených vrátek: 3. května 15–17 h</p><p><strong>Zápis: 10. května od 14–16 h</strong></p><p>Podrobné informace k zápisu najdete <a href="/info/zapis">zde</a>.</p><p>Chcete-li se na něco zeptat, nebo si domluvit schůzku, kontaktujte zástupkyni ředitelky Kláru Taufarovou <i>koordinator@lesnimarianka.cz</i>.</p><p>Těšíme se na vás i vaše děti!</p>',
    created_at: '2022-04-07T08:05:11.878Z',
    updated_at: '2022-04-07T08:11:46.373Z',
    Datum: null,
    Image: null,
  },
  {
    id: 34,
    Nazev: 'Hledáme pedagoga-průvodce 2022/23',
    Text:
      '<p>Chceš dětem pomáhat objevovat svět?</p><p>Hledáme pedagoga - průvodce na nový školní rok 2022/23.</p><p>co nabízíme:</p><ul><li>skvělý tým a prostředí</li><li>malou skupinu dětí</li><li>práci v přírodě</li><li>zkrácený pracovní úvazek</li><li>příležitosti k dalšímu vzdělávání</li><li>více než 10 let zkušeností</li></ul><p>co potřebujeme:</p><ul><li>zkušenosti s pedagogikou dětí ve věku 3 - 6 let</li><li>radost ze soužití s dětmi a přírodou</li><li>odolnost - nevadí ti být venku za každého počasí</li><li>schopnost spolupracovat v týmu</li><li>flexibilitu a chuť na sobě pracovat</li></ul><p>co se hodí:</p><ul><li>umíš hrát na hudební nástroje, zpíváš, hraješ divadlo či tvoříš</li><li>jsi nadšený milovník přírody, poznáš stopy ve sněhu, ptáky na stromech…</li><li>máš za sebou vzdělávací kurzy, např. Respektovat a být respektován</li></ul><p>Máš pocit, že je to práce šitá pro tebe, ale nesplňuješ vše? Nevadí! Chceš-li se dál učit a pracovat na sobě, podpoříme tě!</p><p>Pošli nám životopis a krátký motivační dopis na <strong>info@lesnimarianka.cz.</strong></p>',
    created_at: '2022-06-08T13:16:01.033Z',
    updated_at: '2022-06-08T13:20:02.187Z',
    Datum: null,
    Image: null,
  },
  {
    id: 35,
    Nazev: 'Pomocník Givt',
    Text:
      '<p>Líbí se vám, co děláme a nakupujete online? Podpořte nás při svých nákupech v e-shopech, aniž by vás to cokoli stálo navíc. Stačí si přidat Pomocníka Givt, který vás upozorní na možnost v daném obchodu přispívat. Stáhnout si ho můžete na našem webu <a href="/onas/sponzori">zde</a> a přes prázdniny nám přispějete 60 Kč. Děkujeme!</p>',
    created_at: '2022-07-22T13:07:51.243Z',
    updated_at: '2022-07-22T13:07:51.252Z',
    Datum: null,
    Image: null,
  },
  {
    id: 36,
    Nazev: 'Kamarád do školky',
    Text:
      '<p>Nabízíme volné místo v naší školce na pravidelnou docházku na dva dny v týdnu - čtvrtky a pátky.</p><p>V případě Vašeho zájmu kontaktujte zástupkyni školy Kláru Taufarovou <a href="mailto:koordinator@lesnimarianka.cz">koordinator@lesnimarianka.cz</a></p><p>Těšíme se!</p>',
    created_at: '2022-09-08T15:42:13.086Z',
    updated_at: '2022-09-08T15:47:17.056Z',
    Datum: null,
    Image: null,
  },
  {
    id: 37,
    Nazev: 'Zvoneček podzim 2022',
    Text:
      '<p>Srdečně zveme na oblíbený kroužek Zvoneček pro děti od 1 do 3 let s doprovodem! Startujeme už <strong>29. září</strong>.</p><p>Setkávat se budeme na naší zahradě ve:</p><p><strong>ČTVRTKY od 9:30 do 11:30</strong>&nbsp;</p><p>Devět dopolední můžete strávit v zahradě a blízkém lese, hrát si, tvořit, zpívat a radovat se společně se svými dětmi či vnoučaty z proměn podzimu.</p><p>Podrobnosti a přihlášku najdete <a href="https://docs.google.com/forms/d/e/1FAIpQLSf1Y6EweGSEb30fGYOwp6K-fcu-tM7559jFa6d7FYqS4d7gtg/viewform?usp=sf_link">zde</a>.</p><p>Těšíme se na vás i vaše děti!</p>',
    created_at: '2022-09-09T08:49:05.375Z',
    updated_at: '2022-09-09T08:50:12.247Z',
    Datum: null,
    Image: null,
  },
  {
    id: 38,
    Nazev: 'PF 2023',
    Text:
      '<p>Přejeme krásné svátky a do nového roku pevná přátelství, zdraví a hodně sil!</p>',
    created_at: '2022-11-15T16:37:19.154Z',
    updated_at: '2022-11-15T16:37:19.166Z',
    Image: {
      name: 'NÁHLED_pf23_upravene2_gj0xwb',
      ext: '.jpg',
      mime: 'image/jpeg',
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1671793330/N%C3%81HLED_pf23_upravene2_gj0xwb.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      created_by: 1,
      updated_by: 1,
      created_at: '2022-11-15T16:37:12.570Z',
      updated_at: '2022-11-15T16:37:12.603Z',
    },
  },
  {
    id: 39,
    Nazev: 'Zvoneček jaro 2023',
    Text:
      '<p>Srdečně zveme na oblíbený kroužek Zvoneček pro děti od 1 do 3 let s doprovodem! Startujeme už 15. března.</p><p>Setkávat se budeme na naší zahradě ve:</p><p>STŘEDY od 9:30 do 11:30</p><p>Dvanáct dopolední můžete strávit v zahradě a blízkém lese, hrát si, tvořit, zpívat a radovat se společně se svými dětmi či vnoučaty z probouzení jarní přírody.</p><p>Podrobnosti a přihlášku najdete <a href="https://docs.google.com/forms/d/e/1FAIpQLSf1Y6EweGSEb30fGYOwp6K-fcu-tM7559jFa6d7FYqS4d7gtg/viewform">zde</a>.</p><p>Těšíme se na vás i vaše děti!</p>',
    created_at: '2022-11-15T16:37:19.154Z',
    updated_at: '2022-11-15T16:37:19.166Z',
    Image: null,
  },
  {
    id: 40,
    Nazev: 'Tábory 2023',
    Text:
      '<p>Také už se nemůžete dočkat léta a vaše děti prázdninových dobrodružství?&nbsp;</p><p>Srdečně zveme na naše příměstské tábory!</p><p>Podrobnosti najdete <a href="https://lesnikavyl.cz/tabory">zde</a>.</p>',
    created_at: '2022-03-14T15:07:22.812Z',
    updated_at: '2022-03-14T15:08:11.512Z',
    Image: {
      url: 'https://lesnikavyl.cz/images/tabory23.jpg',
    },
  },
];

export const clenove = [
  {
    id: 2,
    Jmeno: 'Klára Taufarová',
    Pozice: 'zástupkyně ředitelky',
    Popis:
      '<p>Vyrostla jsem v&nbsp;Ostravě, vystudovala jsem Obecnou biologii na Masarykově univerzitě v Brně.&nbsp;</p><p>Díky mým zájmům jsem získala zkušenosti s vedením tábornického oddílu a táborů maminek s&nbsp;dětmi. Obojí zahrnuje táboření a život v&nbsp;souladu s přírodou, práci s&nbsp;dětmi předškolního i školního věku, koordinaci rodičů a jejich dobrovolnické činnosti, vedení účetnictví a řízení projektů.</p><p>Jsem maminka tří dětí&nbsp;a ty mi jasně dávají najevo, co je pro děti jejich věku důležité.</p><p>Na lesní školce se mi líbí, že děti nemusí čekat na prázdniny, aby prožívaly svá dobrodružství.</p>',
    created_at: '2021-01-02T17:08:33.363Z',
    updated_at: '2021-01-15T08:05:05.557Z',
    Image: {
      id: 14,
      name: 'KT.jpg',
      alternativeText: '',
      caption: '',
      width: 591,
      height: 591,
      formats: {
        small: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1609608501/small_KT_f6d2eb5864.jpg',
          hash: 'small_KT_f6d2eb5864',
          mime: 'image/jpeg',
          name: 'small_KT.jpg',
          path: null,
          size: 32.83,
          width: 500,
          height: 500,
          provider_metadata: {
            public_id: 'small_KT_f6d2eb5864',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1609608500/thumbnail_KT_f6d2eb5864.jpg',
          hash: 'thumbnail_KT_f6d2eb5864',
          mime: 'image/jpeg',
          name: 'thumbnail_KT.jpg',
          path: null,
          size: 4.24,
          width: 156,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_KT_f6d2eb5864',
            resource_type: 'image',
          },
        },
      },
      hash: 'KT_f6d2eb5864',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 43.95,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1609608500/KT_f6d2eb5864.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: { public_id: 'KT_f6d2eb5864', resource_type: 'image' },
      created_at: '2021-01-02T17:28:22.093Z',
      updated_at: '2021-01-02T17:28:22.132Z',
    },
  },
  {
    id: 1,
    Jmeno: 'Klára Krchňavá',
    Pozice: 'zakladatelka a ředitelka',
    Popis:
      '<p>Narodila se a své dětství prožila v&nbsp;jižních Čechách. Vystudovala obor Speciální pedagogika na UK v&nbsp;Praze a obor Etika na Teologické fakultě Jihočeské univerzity v&nbsp;Českých Budějovicích. Vzdělání si doplňuje dalšími kurzy. Velkou inspirací jsou pro ni její tři báječné děti.</p><p>Je zakladatelkou Dětského lesního klubu Stromík v&nbsp;Pozořicích (2010) a Lesní mateřské školy Mariánka v&nbsp;Brně-Líšni (2012). Stará se o organizaci aktivit, o provoz zázemí a komunikaci s&nbsp;rodiči, je pedagog. Při obou školkách založila a střídavě také vede kroužek Výletníček a Zvoneček pro maminky s&nbsp;dětmi do tří let. V rámci celé organizace se stará o rozvoj a směřování projektů.</p><p>Spolupracuje s Asociací lesních mateřských škol na dalším vzdělávání pedagogů a organizačního vedení.</p>',
    created_at: '2021-01-02T17:07:52.237Z',
    updated_at: '2021-01-15T08:02:17.405Z',
    Image: {
      id: 13,
      name: 'KK.jpg',
      alternativeText: '',
      caption: '',
      width: 328,
      height: 328,
      formats: {
        thumbnail: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1609608500/thumbnail_KK_b5199eba7c.jpg',
          hash: 'thumbnail_KK_b5199eba7c',
          mime: 'image/jpeg',
          name: 'thumbnail_KK.jpg',
          path: null,
          size: 5.79,
          width: 156,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_KK_b5199eba7c',
            resource_type: 'image',
          },
        },
      },
      hash: 'KK_b5199eba7c',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 20.01,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1609608500/KK_b5199eba7c.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: { public_id: 'KK_b5199eba7c', resource_type: 'image' },
      created_at: '2021-01-02T17:28:21.281Z',
      updated_at: '2021-01-02T17:28:21.320Z',
    },
  },
  {
    id: 6,
    Jmeno: 'Peťa Janečková',
    Pozice: 'chůva',
    Popis:
      '<p>Narodila jsem se ve Zlíně. V dětství jsem hodně jezdila k prarodičům na vesnici, což mě jistě ovlivnilo. Zažila jsem tam spolu se sestrou a sestřenicemi hodiny a hodiny volné hry :)</p><p>V Brně jsem vystudovala obory sociální práce a vzdělávání dospělých. Přesto teď učím děti a často i ony mě.&nbsp;</p><p>Absolvovala jsem kurzy Respektovat a být respektován a Pedagogicko-psychologické minimum.&nbsp;</p><p>První měsíce ve školce mi trochu připomínaly letní salesiánské tábory, kterých jsem se účastnila jako vedoucí. Ty byly na louce u lesa a potoka a vždy byly úžasné! Tak doufám, že naše děti ve školce budou moci zažít podobné věci, které jsem já prožila tam.&nbsp;</p><p>&nbsp;</p><p><i>Motto: "Správně vidíme jen srdcem. Co je důležité, je očím neviditelné." Antoine de Saint-Exupéry</i></p>',
    created_at: '2021-01-02T17:16:23.063Z',
    updated_at: '2021-03-05T07:23:25.708Z',
    Image: {
      id: 15,
      name: 'PEŤA.jpg',
      alternativeText: '',
      caption: '',
      width: 226,
      height: 226,
      formats: {
        thumbnail: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1609608620/thumbnail_PETA_78282abf36.jpg',
          hash: 'thumbnail_PETA_78282abf36',
          mime: 'image/jpeg',
          name: 'thumbnail_PEŤA.jpg',
          path: null,
          size: 7.4,
          width: 156,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_PETA_78282abf36',
            resource_type: 'image',
          },
        },
      },
      hash: 'PETA_78282abf36',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 14.4,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1609608619/PETA_78282abf36.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'PETA_78282abf36',
        resource_type: 'image',
      },
      created_at: '2021-01-02T17:30:20.848Z',
      updated_at: '2021-01-02T17:30:20.912Z',
    },
  },
  {
    id: 4,
    Jmeno: 'Nya Švehlová',
    Pozice: 'pedagog',
    Popis:
      '<p>"Nechci sedět v klidu a poslouchat. Chci si sama ohmatat svět a zažít ho na vlastní kůži!"</p><p>Vystudovala jsem Střední pedagogickou školu v Brně, Homeopatickou fakultu, kurz Respektovat a být respektován a Průvodce dětí světem. Učila jsem ve státní školce, vychovala pět dětí a prošla s nimi všemi stupni školství. Jsem spoluzakladatelkou alternativní Základní školy Prameny v Rousínově, kde jsem průvodcem dětí pro lesní den. Vedu Ženský kruh v Rousínově, přednáším a věnuji se homeopatické terapii. Studuji waldorfskou pedagogiku a tradiční čínskou medicínu.</p><p>Děti jsou přirozeně zvídavé a touží objevovat a poznávat. Dopřejme jim prostor a čas, aby svět objevovaly vlastním způsobem a svým tempem. Aby mohly rozvíjet své zájmy a touhy tehdy, když to potřebují a když k nim dorostou. Dostatek volnosti a svobody v přírodě, v přirozeném neumělém a netechnickém prostředí, jim dává nekonečné možnosti ke všem možným činnostem a objevům, podněcuje jejich tvořivého ducha a podporuje je fyzicky i psychicky. Vždyť v přírodě jsme doma...</p>',
    created_at: '2021-01-02T17:11:54.515Z',
    updated_at: '2021-01-15T07:58:20.069Z',
    Image: {
      id: 6,
      name: 'NYA.JPG',
      alternativeText: '',
      caption: '',
      width: 800,
      height: 800,
      formats: {
        small: {
          ext: '.JPG',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1609607262/small_NYA_767164bd10.jpg',
          hash: 'small_NYA_767164bd10',
          mime: 'image/jpeg',
          name: 'small_NYA.JPG',
          path: null,
          size: 55.13,
          width: 500,
          height: 500,
          provider_metadata: {
            public_id: 'small_NYA_767164bd10',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.JPG',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1609607261/medium_NYA_767164bd10.jpg',
          hash: 'medium_NYA_767164bd10',
          mime: 'image/jpeg',
          name: 'medium_NYA.JPG',
          path: null,
          size: 119.82,
          width: 750,
          height: 750,
          provider_metadata: {
            public_id: 'medium_NYA_767164bd10',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.JPG',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1609607260/thumbnail_NYA_767164bd10.jpg',
          hash: 'thumbnail_NYA_767164bd10',
          mime: 'image/jpeg',
          name: 'thumbnail_NYA.JPG',
          path: null,
          size: 6.69,
          width: 156,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_NYA_767164bd10',
            resource_type: 'image',
          },
        },
      },
      hash: 'NYA_767164bd10',
      ext: '.JPG',
      mime: 'image/jpeg',
      size: 139.43,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1609607260/NYA_767164bd10.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'NYA_767164bd10',
        resource_type: 'image',
      },
      created_at: '2021-01-02T17:07:42.920Z',
      updated_at: '2021-01-02T17:07:42.989Z',
    },
  },
  {
    id: 5,
    Jmeno: 'Zdislava Müllnerová',
    Pozice: 'pedagog',
    Popis:
      '<p>Vystudovala jsem obor Učitelství pro mateřské školy na Masarykově univerzitě a dále navazující magisterské studium v oboru Sociální pedagogiky a volný čas také na MU. Absolvovala jsem kurz Montessori pedagogika I, ZdrSem MAMA (zdravotní kurz) a Original Play.</p><p>Ještě před nástupem do Mariánky jsem se věnovala dětem a mládeži ve svém volném čase. Ať už to byla organizace táborů, animátorství na akcích pro rodiny nebo individuální hlídání.</p><p>Je skvělé být s dětmi a podporovat je v jejich vývoji ke zralé osobnosti. Nejenže vidíte stále výsledky svého úsilí, ale rostete společně s nimi.&nbsp;Vzhledem k tomu, že se děti učí především ze svých bezprostředních zkušeností, tak je příroda jistě nejpodnětnějším prostředím k předškolnímu vzdělávání. Navíc můžu z osobní zkušenosti potvrdit pozitivní vliv na zdraví ;)</p>',
    created_at: '2021-01-02T17:15:48.406Z',
    updated_at: '2021-02-24T16:06:14.888Z',
    Image: {
      id: 11,
      name: 'ZM.jpg',
      alternativeText: '',
      caption: '',
      width: 400,
      height: 400,
      formats: {
        thumbnail: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1614182770/thumbnail_ZM_931cdfaa06.jpg',
          hash: 'thumbnail_ZM_931cdfaa06',
          mime: 'image/jpeg',
          name: 'thumbnail_ZM.jpg',
          path: null,
          size: 6.98,
          width: 156,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_ZM_931cdfaa06',
            resource_type: 'image',
          },
        },
      },
      hash: 'ZM_931cdfaa06',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 33.84,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1614182769/ZM_931cdfaa06.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: { public_id: 'ZM_931cdfaa06', resource_type: 'image' },
      created_at: '2021-01-02T17:15:37.287Z',
      updated_at: '2021-02-24T16:06:10.864Z',
    },
  },
];

export const sponzori = [
  {
    id: 3,
    Nazev: 'MŠMT',
    Vyska: null,
    created_at: '2021-01-18T21:26:06.306Z',
    updated_at: '2021-01-24T11:27:42.444Z',
    Poradi: 3,
    Odkaz: 'http://www.msmt.cz/',
    Okraj: null,
    Popis: null,
    Image: {
      id: 24,
      name: 'msmt.jpg',
      alternativeText: '',
      caption: '',
      width: 653,
      height: 367,
      formats: {
        small: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1611005099/small_msmt_e0e6a7cb57.jpg',
          hash: 'small_msmt_e0e6a7cb57',
          mime: 'image/jpeg',
          name: 'small_msmt.jpg',
          path: null,
          size: 13.61,
          width: 500,
          height: 281,
          provider_metadata: {
            public_id: 'small_msmt_e0e6a7cb57',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1611005098/thumbnail_msmt_e0e6a7cb57.jpg',
          hash: 'thumbnail_msmt_e0e6a7cb57',
          mime: 'image/jpeg',
          name: 'thumbnail_msmt.jpg',
          path: null,
          size: 5.14,
          width: 245,
          height: 138,
          provider_metadata: {
            public_id: 'thumbnail_msmt_e0e6a7cb57',
            resource_type: 'image',
          },
        },
      },
      hash: 'msmt_e0e6a7cb57',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 18.06,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1611005097/msmt_e0e6a7cb57.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'msmt_e0e6a7cb57',
        resource_type: 'image',
      },
      created_at: '2021-01-18T21:24:59.477Z',
      updated_at: '2021-01-18T21:24:59.619Z',
    },
  },
  {
    id: 4,
    Nazev: 'Avast',
    Vyska: null,
    created_at: '2021-01-18T21:26:22.918Z',
    updated_at: '2021-01-24T11:27:50.204Z',
    Poradi: 4,
    Odkaz: 'https://foundation.avast.com/',
    Okraj: null,
    Popis: null,
    Image: {
      id: 25,
      name: 'avast.png',
      alternativeText: '',
      caption: '',
      width: 142,
      height: 78,
      formats: null,
      hash: 'avast_63553e671f',
      ext: '.png',
      mime: 'image/png',
      size: 4.71,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1611005180/avast_63553e671f.png',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'avast_63553e671f',
        resource_type: 'image',
      },
      created_at: '2021-01-18T21:26:20.824Z',
      updated_at: '2021-01-18T21:26:20.904Z',
    },
  },
  {
    id: 6,
    Nazev: 'Buran',
    Vyska: null,
    created_at: '2021-01-18T21:26:56.384Z',
    updated_at: '2021-01-24T11:28:15.083Z',
    Poradi: 6,
    Odkaz: 'http://www.buranteatr.cz/',
    Okraj: null,
    Popis: null,
    Image: {
      id: 27,
      name: 'buran.png',
      alternativeText: '',
      caption: '',
      width: 800,
      height: 406,
      formats: {
        small: {
          ext: '.png',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1611005213/small_buran_1979f5db18.png',
          hash: 'small_buran_1979f5db18',
          mime: 'image/png',
          name: 'small_buran.png',
          path: null,
          size: 18.05,
          width: 500,
          height: 254,
          provider_metadata: {
            public_id: 'small_buran_1979f5db18',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.png',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1611005212/medium_buran_1979f5db18.png',
          hash: 'medium_buran_1979f5db18',
          mime: 'image/png',
          name: 'medium_buran.png',
          path: null,
          size: 30.42,
          width: 750,
          height: 381,
          provider_metadata: {
            public_id: 'medium_buran_1979f5db18',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.png',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1611005211/thumbnail_buran_1979f5db18.png',
          hash: 'thumbnail_buran_1979f5db18',
          mime: 'image/png',
          name: 'thumbnail_buran.png',
          path: null,
          size: 8.5,
          width: 245,
          height: 124,
          provider_metadata: {
            public_id: 'thumbnail_buran_1979f5db18',
            resource_type: 'image',
          },
        },
      },
      hash: 'buran_1979f5db18',
      ext: '.png',
      mime: 'image/png',
      size: 22.03,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1611005211/buran_1979f5db18.png',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'buran_1979f5db18',
        resource_type: 'image',
      },
      created_at: '2021-01-18T21:26:53.734Z',
      updated_at: '2021-01-18T21:26:53.814Z',
    },
  },
  {
    id: 7,
    Nazev: 'Activity',
    Vyska: null,
    created_at: '2021-01-18T21:27:12.702Z',
    updated_at: '2021-01-24T11:34:22.869Z',
    Poradi: 7,
    Odkaz: 'http://www.toactivity.cz/',
    Okraj: 2,
    Popis: null,
    Image: {
      id: 28,
      name: 'activity.png',
      alternativeText: '',
      caption: '',
      width: 229,
      height: 67,
      formats: null,
      hash: 'activity_c91bf3d9cf',
      ext: '.png',
      mime: 'image/png',
      size: 24.61,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1611005230/activity_c91bf3d9cf.png',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'activity_c91bf3d9cf',
        resource_type: 'image',
      },
      created_at: '2021-01-18T21:27:10.644Z',
      updated_at: '2021-01-18T21:27:10.717Z',
    },
  },
  {
    id: 5,
    Nazev: 'Livebox',
    Vyska: '',
    created_at: '2021-01-18T21:26:39.492Z',
    updated_at: '2021-01-24T11:35:20.327Z',
    Poradi: 5,
    Odkaz: 'http://www.livebox.cz/',
    Okraj: 2,
    Popis: null,
    Image: {
      id: 26,
      name: 'livebox.gif',
      alternativeText: '',
      caption: '',
      width: 183,
      height: 46,
      formats: null,
      hash: 'livebox_3cf08dc656',
      ext: '.gif',
      mime: 'image/gif',
      size: 1.7,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1611005196/livebox_3cf08dc656.gif',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'livebox_3cf08dc656',
        resource_type: 'image',
      },
      created_at: '2021-01-18T21:26:37.417Z',
      updated_at: '2021-01-18T21:26:37.489Z',
    },
  },
  {
    id: 2,
    Nazev: 'Brno',
    Vyska: '',
    created_at: '2021-01-18T21:24:28.213Z',
    updated_at: '2021-01-24T11:35:24.906Z',
    Poradi: 2,
    Odkaz: 'https://www.brno.cz/',
    Okraj: 2,
    Popis: null,
    Image: {
      id: 23,
      name: 'brno.svg',
      alternativeText: '',
      caption: '',
      width: 310,
      height: 72,
      formats: null,
      hash: 'brno_9d297c621b',
      ext: '.svg',
      mime: 'image/svg+xml',
      size: 3.22,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1611005063/brno_9d297c621b.svg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'brno_9d297c621b',
        resource_type: 'image',
      },
      created_at: '2021-01-18T21:24:25.414Z',
      updated_at: '2021-01-18T21:24:25.495Z',
    },
  },
  {
    id: 1,
    Nazev: 'Brno-Líšeň',
    Vyska: null,
    created_at: '2021-01-18T21:24:02.435Z',
    updated_at: '2021-03-07T11:47:29.992Z',
    Poradi: 1,
    Odkaz: 'http://www.brno-lisen.cz/',
    Okraj: null,
    Popis: 'Brno-Líšeň',
    Image: {
      id: 22,
      name: 'lisen.png',
      alternativeText: '',
      caption: '',
      width: 876,
      height: 1024,
      formats: {
        large: {
          ext: '.png',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1611005018/large_lisen_b7c5dd5162.png',
          hash: 'large_lisen_b7c5dd5162',
          mime: 'image/png',
          name: 'large_lisen.png',
          path: null,
          size: 106.06,
          width: 855,
          height: 1000,
          provider_metadata: {
            public_id: 'large_lisen_b7c5dd5162',
            resource_type: 'image',
          },
        },
        small: {
          ext: '.png',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1611005020/small_lisen_b7c5dd5162.png',
          hash: 'small_lisen_b7c5dd5162',
          mime: 'image/png',
          name: 'small_lisen.png',
          path: null,
          size: 42.62,
          width: 428,
          height: 500,
          provider_metadata: {
            public_id: 'small_lisen_b7c5dd5162',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.png',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1611005019/medium_lisen_b7c5dd5162.png',
          hash: 'medium_lisen_b7c5dd5162',
          mime: 'image/png',
          name: 'medium_lisen.png',
          path: null,
          size: 72.77,
          width: 642,
          height: 750,
          provider_metadata: {
            public_id: 'medium_lisen_b7c5dd5162',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.png',
          url:
            'https://res.cloudinary.com/marianka/image/upload/v1611005016/thumbnail_lisen_b7c5dd5162.png',
          hash: 'thumbnail_lisen_b7c5dd5162',
          mime: 'image/png',
          name: 'thumbnail_lisen.png',
          path: null,
          size: 12.65,
          width: 133,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_lisen_b7c5dd5162',
            resource_type: 'image',
          },
        },
      },
      hash: 'lisen_b7c5dd5162',
      ext: '.png',
      mime: 'image/png',
      size: 60.11,
      url:
        'https://res.cloudinary.com/marianka/image/upload/v1611005015/lisen_b7c5dd5162.png',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'lisen_b7c5dd5162',
        resource_type: 'image',
      },
      created_at: '2021-01-18T21:23:40.716Z',
      updated_at: '2021-01-18T21:23:40.846Z',
    },
  },
];

export const stranky = [
  {
    id: 1,
    Nazev: 'Kontakt1',
    Text: '<h3>Kde nás najdete</h3><p>ulice Samoty, Brno-Líšeň</p>',
    created_at: '2021-01-02T19:17:18.052Z',
    updated_at: '2021-01-02T19:17:18.069Z',
  },
  {
    id: 7,
    Nazev: 'Projekty 1',
    Text:
      '<h3>Lesní mateřská škola Mariánka</h3><p><br>Zdroj podpory: Operační program Výzkum, vývoj a vzdělávání, MŠMT</p><p>Název příjemce podpory: Lesní mateřská škola Mariánka</p><p>Datum zahájení realizace: 1. 9. 2019</p><p>Datum plánovaného ukončení: 31. 8. 2021</p><p>Název specifického cíle: Zvýšení kvality předškolního vzdělávání včetně usnadnění přechodu dětí na ZŠ</p><p>Obsah projektu: Projekt je zaměřen na jedno z/kombinaci následujících témat: personální podpora, osobnostně profesní rozvoj pedagogů, společné vzdělávání dětí, podpora extrakurikulárních/rozvojových aktivit, aktivity rozvíjející ICT, spolupráce s rodiči dětí, spolupráce s veřejností.</p><h3>Digitalizujeme školu</h3><div style="display: flex; justify-content: center"><img src="/images/digitalizujeme.png"></div><p>&nbsp;</p>',
    created_at: '2021-01-18T19:14:17.852Z',
    updated_at: '2021-10-01T11:19:13.470Z',
  },
  {
    id: 5,
    Nazev: 'Zázemí 1',
    Text:
      '<p>Zázemí Mariánky tvoří rozlehlá zahrada s chatkou a týpím. Na zahradě jsou prolézačky, na záhoncích pěstujeme bylinky i zeleninu. U chatky je zastřešená pergola, kde můžeme obědvat nebo tvořit, na stěně tabule, kde můžeme malovat či psát a před chatkou kuchyňka na vaření dobrot z písku a listí.</p>',
    created_at: '2021-01-18T19:13:21.939Z',
    updated_at: '2021-02-07T18:29:25.127Z',
  },
  {
    id: 23,
    Nazev: 'Tipy pro rodiče',
    Text:
      '<p>Už vám docházejí nápady? Nevadí!&nbsp;</p><p>Naši lektoři a pedagogové pro vás chystají pestrý nápadník básniček, her a tvoření do lesa i na doma. Během roku se budou s ročními obdobími měnit i naše tipy tak, abyste je mohli rovnou vyzkoušet.<br>Za pomoc děkujeme také kouzelníkovi se zvukem a obrazem <strong>Kamilu Šlapalovi</strong>, <a href="http://www.cafilm.cz/cz/">Craft Art Film</a>.</p><h3>Básničky a povídačky</h3><ul><li><a href="https://lesnikavyl.cz/files/jarni_basnicka.png">jarní básnička</a></li><li><a href="https://lesnikavyl.cz/files/Pampelina.pdf">Jak vařila Pampelína - jarní obrázkový příběh</a></li></ul><h3>Hry nejen do lesa</h3><ul><li><a href="https://lesnikavyl.cz/files/hry.png">3 hry (nejen) na jaro</a></li><li><a href="https://lesnikavyl.cz/files/pozorovani_prirody.png">pozorování přírody</a> (jaro)</li></ul><h3>Tvoření</h3><ul><li><a href="https://lesnikavyl.cz/files/krmitka.png">krmítka ze šišek</a></li></ul><h3>Do ouška</h3><ul><li><a href="https://lesnikavyl.cz/files/Tapy_Tap.mp3">Ťapy ťap</a></li><li><a href="/files/mami.mp3">Mami, proč jsi mi neřekla</a></li><li><a href="/files/snist.mp3">Co můžeš sníst dnes</a></li><li><a href="/files/tajne_heslo.mp3">Tajné heslo</a></li><li><a href="/files/kacatko.mp3">O ošklivém káčátku</a></li><li><a href="/files/tri_prasatka.mp3">O třech prasátkách</a></li></ul><h3>Svátky a tradice</h3><ul><li><a href="/files/morana.pdf">pálení Morany</a></li><li><a href="/files/jaro2.pdf">vítání jara</a></li></ul><p>&nbsp;</p>',
    created_at: '2021-03-06T13:00:13.206Z',
    updated_at: '2021-04-14T06:38:43.915Z',
  },
  {
    id: 15,
    Nazev: 'Aktivity Kavylu',
    Text:
      '<p><a href="https://www.lesnikavyl.cz/">Spolek Kavyl</a> z.s., zřizovatel Mariánky, pořádá v našem zázemí volnočasové kroužky a letní příměstské tábory. V Líšni můžete také navštívit přednášky o výchově a vzdělávání.</p>',
    created_at: '2021-01-18T19:26:35.900Z',
    updated_at: '2021-03-18T10:21:06.640Z',
  },
  {
    id: 11,
    Nazev: 'Kroužky',
    Text:
      '<h3>Zvoneček</h3><p>Na jaře, na podzim a v zimě probíhá cyklus setkání určených pro děti do 3 let v doprovodu rodiče nebo jiné blízké osoby. Od malička děti poznávají přírodu hravou formou - písničky, básničky, tvoření, hry, procházky. Hrajeme si v naší kouzelné zahradě a v blízkém lese pod vedením lektora z lesní školky.</p><h3>Aktuální cyklus</h3><p>Přihlašovací formulář <a href="https://docs.google.com/forms/d/e/1FAIpQLSf1Y6EweGSEb30fGYOwp6K-fcu-tM7559jFa6d7FYqS4d7gtg/viewform?usp=sf_link">zde</a>.</p><p>Jarní cyklus startuje už 15. 3. a budeme se setkávat až do konce května. Chcete-li se na něco zeptat, pište na aktivity@lesnikavyl.cz Těšíme se na vás i vaše děti!</p>',
    created_at: '2021-01-18T19:16:09.692Z',
    updated_at: '2022-03-21T13:12:45.418Z',
  },
  {
    id: 13,
    Nazev: 'Přednášky',
    Text:
      '<p>Srdečně zveme také na přednášky pro rodiče i širokou veřejnost o vzdělávání a výchově. Pozvánky najdete u nás a na <a href="https://www.lesnikavyl.cz/">webu</a> či <a href="https://www.facebook.com/spolekKavyl">FB</a> spolku Kavyl.</p>',
    created_at: '2021-01-18T19:16:34.464Z',
    updated_at: '2021-01-20T15:25:43.732Z',
  },
  {
    id: 10,
    Nazev: 'Naše pravidla',
    Text:
      '<ol><li>Nenosíme do školky žádné sladkosti, sladké čaje a hračky.</li><li>Chodíme do školky zdravé.</li><li>Máme dostatečné vybavení do přírody s ohledem na roční dobu.</li><li>Přicházíme do školky včas a rodiče si nás také včas vyzvedávají.</li><li>Rodiče jsou v době pobytu dítěte ve školce na telefonu pro případ zhoršení zdravotního stavu, úrazu, změny místa vyzvedávání apod.</li></ol>',
    created_at: '2021-01-18T19:15:47.960Z',
    updated_at: '2021-03-05T09:34:41.589Z',
  },
  {
    id: 6,
    Nazev: 'Program',
    Text:
      '<p>Převážná většina programu v Mariánce probíhá celoročně a za každého počasí venku, tj. na zahradě s ovocnými stromy v našem zázemí a v blízkém smíšeném lese. Les vnímáme jako přirozené, člověkem (a pedagogem) nepřipravené prostředí, které samo o sobě nabízí prostor pro kreativitu, rytmus a harmonii. V přírodě člověk snadno a přirozeně vnímá střídání ročních období, rytmus přirozeného světla a cítí vliv těchto změn na nás samotné. Proto jsme náš program uzpůsobili koloběhu roku a tradicím. Každoročně se věnujeme slavnostem inspirovaným Waldorfskou pedagogikou, které s každým novým rokem s dětmi prožíváme a znovuvytváříme podle aktuálních potřeb skupiny dětí i dospělých.</p><h3>Harmonogram dne:</h3><figure class="table"><table><tbody><tr><td>7:30 - 8:30</td><td>příjezd dětí s rodiči, převzetí dětí</td></tr><tr><td>8:45 - 9:00</td><td>přivítání s dětmi, ranní diskuzní kruh, seznámení s programem</td></tr><tr><td>9:00 - 10:00</td><td>cesta do lesa, dopolední řízená činnost v lese</td></tr><tr><td>10:00 - 10:30</td><td>dopolední svačina dětí, volná hra dětí</td></tr><tr><td>10:30 - 11:30</td><td>společná hra dětí v lese, pedagog je dětem průvodcem</td></tr><tr><td>11:30 - 12:00</td><td>zpáteční cesta do zázemí</td></tr><tr><td>12:00 - 12:45</td><td>PŘESTÁVKA NA OBĚD</td></tr><tr><td>12:45 - 13:30</td><td>polední odpočinek, klidová činnost</td></tr><tr><td>13:30 - 15:30</td><td>odpolední činnost a volná hra dětí na zahradě, svačina dle potřeb dětí</td></tr><tr><td>15:30 - 16:00</td><td>předání dětí rodičům</td></tr></tbody></table></figure>',
    created_at: '2021-01-18T19:13:36.276Z',
    updated_at: '2021-03-10T22:52:54.920Z',
  },
  {
    id: 8,
    Nazev: 'Co s sebou 1',
    Text:
      '<h3>Oblečení</h3><p>K ochraně před sluncem, poškrábáním a klíšťaty nejlépe poslouží dlouhé nohavice a rukávy. Nezbytná je pokrývka hlavy, nejlépe chránící i krk.</p><p>Náhradní oblečení, které zůstává v místě zázemí: spodní prádlo, ponožky, punčochy, tepláky, tričko, mikina, náhradní obuv na ven, papuče.</p><p>Náhradní oblečení i obuv je potřeba viditelně označit a pravidelně doplňovat.</p>',
    created_at: '2021-01-18T19:14:54.415Z',
    updated_at: '2021-02-07T18:41:46.339Z',
  },
  {
    id: 18,
    Nazev: 'Zázemí 2',
    Text:
      '<p>Za humny máme smíšený les plný dobrodružsví - jsou tu prolézačky, houpačky i schovky, můžeme počítat šišky, kreslit do jehličí, v zimě pátrat po stopách ve sněhu a bobovat na lesních cestách. Staráme se o zvířátka, rostliny i studánky. Začíná tu také Moravský kras, do kterého vyrážíme na výpravy.</p>',
    created_at: '2021-02-07T18:27:09.177Z',
    updated_at: '2021-02-07T18:27:09.182Z',
  },
  {
    id: 19,
    Nazev: 'Program 2',
    Text:
      '<h3>Kroužky a předškolní příprava</h3><p>V rámci kroužků a organizovaných aktivit nabízíme terapeutické bubnování, animoterapii, hru s výtvarným materiálem, přírodovědu, práci s ostrými nástroji, vyprávění příběhů a program s anglicky mluvícími rodilými mluvčími.<br>Předškolní přípravě se věnujeme podle potřeb dítěte v rámci aktivit zařazených do běžného chodu dne. Zároveň probíhá také soustředěná příprava - děti zpracovávají předškolácké listy, rozvíjíme cíleně grafomotoriku, předmatematické představy, sluchové vnímání, s dětmi logopedicky pracujeme. Absolventi naší školky úspěšně zvládají přechod na základní školu.</p>',
    created_at: '2021-02-07T18:30:21.415Z',
    updated_at: '2021-02-07T18:30:21.420Z',
  },
  {
    id: 20,
    Nazev: 'Projekty 2',
    Text:
      '<h3>Od studánky k Říčce (2021)</h3><p>Od studánky k Říčce je celoroční projekt zaměřený na environmentální vzdělávání dětí navštěvujících Lesní mateřskou školu Mariánku.&nbsp; Děti se metodami prožitkového učení seznámí s významem vody pro celý ekosystém.</p><p>Projekt je podpořen Magistrátem města Brna.</p>',
    created_at: '2021-02-07T18:35:23.478Z',
    updated_at: '2021-02-07T18:35:23.483Z',
  },
  {
    id: 21,
    Nazev: 'Co s sebou 2',
    Text:
      '<h3>Co v zimě</h3><p>Zásada <strong>cibulovitého vrstvení</strong>, tj. víc vrstev, které se mohou podle potřeby měnit, vysvlékat nebo oblékat.</p><h4>Ochrana těla:</h4><ul><li>spodní vrstva - hřejivá, ideální je vlna</li><li>uprostřed 1 – 3 vrstvy z fleecového materiálu, které hřejí a zároveň izolují; vrstvy neprofouknou a udržují stabilní teplotu</li><li>svrchní vrstva má především funkci nepromokavou</li></ul><h4>Ochrana nohou:</h4><ul><li>vrstvení ponožek</li><li>mít na nepromokavých kalhotách gumičku, která se dá přetáhnout přes boty, nebo dát dítěti návleky na boty</li><li>boty nejlépe s membránou a pevné kotníčkové</li><li>za deště a bláta lze použít holínky</li></ul><h3>Co do batohu</h3><p>Batoh by měl být z pevného a nejlépe nepromokavého materiálu, s nastavitelnými pruhy. Velmi dobrá je náprsní přezka, která zajistí, že dětem při pohybu batoh nepadá z ramen. Do batůžku přijde podložka na sezení – stačí ustřižená karimatka, svačinka, pití, kapesník, náhradní spodní prádlo a ponožky, sáček na poklady z lesa; v zimě navíc náhradní rukavice.&nbsp;</p>',
    created_at: '2021-02-07T18:41:41.068Z',
    updated_at: '2021-02-07T18:41:41.074Z',
  },
  {
    id: 16,
    Nazev: 'Paticka',
    Text:
      '<h4><a href="mailto:info@lesnimarianka.cz">info@lesnimarianka.cz</a></h4><h4>Brno-Líšeň, ulice Samoty</h4><h4>Bus č. 58, zastávka Kubelíkova</h4><h4><a href="tel:+420777145343">777 145 343</a></h4><h4><a href="https://www.facebook.com/lmsMarianka">lmsMarianka</a></h4>',
    created_at: '2021-01-23T13:03:37.353Z',
    updated_at: '2021-01-28T14:51:01.354Z',
  },
  {
    id: 3,
    Nazev: 'Zápis',
    Text:
      '<h3>Informace k zápisu</h3><p><i>Zápis pro školní rok 2022/23</i></p><ul><li><i>Den otevřených vrátek: 3. května 15–17 h</i></li><li><i>Zápis: 10. května 14–16 h</i></li></ul><p>Do naší lesní mateřské školy jsou přijímány děti ve věku 3 - 6 let do maximální kapacity 16 dětí.</p><h3>Postup pro přihlašování</h3><ol><li>vyplňte předběžný <a href="https://docs.google.com/forms/d/e/1FAIpQLSfYuL6PzcOU4h2gvStwV_glqv3qVpoPmJZa0FQOK6iroaEMhw/viewform?fbclid=IwAR1mTUNGjBxXV5V5SoCzsp_DdPnfv6byLMs6Pn1Ul1hWIGKhMMNP-LXpd94">nezávazný vstupní dotazník</a></li><li>pozveme vás na informační schůzku, můžete se také k nám přijít podívat na Den otevřených dveří</li><li>stáhněte si žádost o přijetí a dotazník v záložce <a href="/onas/dokumenty">Dokumenty</a></li><li>nechte si žádost potvrdit od lékaře</li><li>vyplněnou žádost, dotazník a kopii rodného listu nám doručte:</li></ol><ul><li>buď <strong>osobně</strong> v době zápisu <strong>10. května 2022 od 14 do 16 h</strong></li><li>nebo <strong>po předchozí osobní schůzce poštou nebo datovou schránkou</strong> v termínu od <strong>2. – 16. května 2022&nbsp;</strong></li></ul><p>&nbsp; &nbsp; &nbsp; 6. začátkem června dostanete rozhodnutí o přijetí</p><p><strong>Aktuální termíny</strong> Dne otevřených dveří i zápisu najdete na našem webu a <a href="https://www.facebook.com/D%C4%9Btsk%C3%BD-lesn%C3%AD-klub-Mari%C3%A1nka-443991749006997">FB</a>.&nbsp;</p><p>Chcete-li vaše dítě přihlásit v průběhu školního roku, informujte se u zástupkyně ředitelky o volných místech.&nbsp;</p><p>Před podáním žádosti se prosím seznamte s obsahem našich webových stránek a dokumentů. Vedle praktických informací o nás, programu i provozu, si na webu můžete přečíst také všechny důležité dokumenty - provozní a školní řád, školní vzdělávací program, podrobné podmínky pro přijímání dětí a další.&nbsp;</p><p>Upozorňujeme, že LMŠ Mariánka přijímá děti, které jsou řádně očkované (rodiče dodají potvrzení od lékaře, nebo potvrzení o zdravotní kontraindikaci podle § 50 zák. č. 258/2000 Sb. o ochraně veřejného zdraví).</p><p>Informace k poplatkům za vzdělávání najdete v záložce <a href="/info/cenik">Ceník a stravování</a>.&nbsp;</p><p>Na přijetí dítěte do LMŠ Mariánka není nárok. O přijetí dětí rozhoduje ředitelka LMŠ podle <a href="/files/kriteria_prijeti_2022.pdf">stanovených kritérií</a>.&nbsp;</p><p>Chcete-li<strong> si vyzkoušet</strong>, jaké to je strávit dopoledne s dětmi v lese, můžete se přihlásit do <strong>kroužku Zvoneček</strong>, který v zázemí školky pravidelně pořádá zřizovatel spolek Kavyl z.s. Kroužek probíhá jednou týdně a je určený pro děti do 3 let s doprovodem. Více na <a href="https://www.lesnikavyl.cz/dalsiaktivity/volnocas">webu spolku</a>.&nbsp;</p><p><strong>V případě dotazů</strong> můžete zavolat nebo napsat zástupkyni ředitelky LMŠ Kláře Taufarové:&nbsp;<br>604 536 796, koordinator@lesnimarianka.cz</p>',
    created_at: '2021-01-18T19:12:49.535Z',
    updated_at: '2022-04-07T07:54:17.109Z',
  },
  {
    id: 22,
    Nazev: 'Jak se žije',
    Text:
      '<p><a href="/images/jsz_rozcestnik.jpg">Žijeme v bezpečném světě.</a></p><ul><li><a href="/images/jsz_pravidla.jpg">Máme jasná pravidla a hranice.</a></li><li><a href="/images/jsz_postup.jpg">Postupujeme od lehkého po obtížné.</a></li><li><a href="/images/jsz_komentujeme.jpg">V rizikových situacích jdeme příkladem a svůj postup nahlas komentujeme.</a></li><li><a href="/images/jsz_riziko.jpg">Pracujeme s bezpečným rizikem.</a></li><li><a href="/images/jsz_bezpecny_prostor.jpg">Vytváříme bezpečný prostor pro svobodný dětský vývoj.</a></li></ul>',
    created_at: '2021-02-28T18:07:12.988Z',
    updated_at: '2021-05-28T07:43:36.011Z',
  },
  {
    id: 17,
    Nazev: 'O Mariánce 2',
    Text:
      '<h2>Co nabízíme:</h2><ul><li>pravidelné <strong>celoroční předškolní vzdělávání</strong> pro skupinku dětí ve věku 3−7 let (max. 15 dětí)</li><li>poskytujeme <strong>povinné předškolní vzdělávání</strong> (děti není třeba přehlašovat na poslední povinný rok předškolní docházky jinam)</li><li>školkovné můžete uplatnit jako slevu na dani</li><li>zázemí tvoří rozlehlá <strong>zahrada a dřevěná chata </strong>kousek od lesa</li><li>LMŠ je pro děti <strong>otevřena každý všední den 7:30 − 16:00 h</strong></li><li>program realizujeme převážně <strong>v přírodě „bez zdí a plotů“ </strong>za přítomnosti dvou pedagogů</li><li>vyrážíme i „do světa” - do divadel, muzeí, za hasiči, na vzdělávací programy nebo na výlety</li><li>naši průvodci mají pedagogické vzdělání a průběžně se dále vzdělávají</li><li>máme dlouholeté zkušenosti s vedením lesních školek</li><li>nabízíme přátelské a otevřené prostředí dětem, rodičům i pedagogům</li></ul><h2>Z čeho vycházíme:</h2><ul><li>z dokumentu <strong>MŠMT - Rámcový vzdělávací program pro předškolní vzdělávání (RVP PV)</strong></li><li>z konceptu <strong>„Respektovat a být respektován"</strong></li><li>naše pedagogická koncepce je založena na myšlence <strong>"s dětmi venku za každého počasí a bez zdí a plotů“,</strong> je zaměřena na plnohodnotný rozvoj kompetencí dětí a na využití rozmanitého prostředí zahrady a lesa</li><li>využíváme prvky <strong>Waldorfské pedagogiky</strong>, inspirujeme se alternativními pedagogickými směry</li></ul>',
    created_at: '2021-02-07T18:25:48.322Z',
    updated_at: '2021-03-24T09:28:51.631Z',
  },
  {
    id: 24,
    Nazev: 'Projekty 0',
    Text: '<h3>Lesní mateřská škola Mariánka II</h3>',
    created_at: '2021-10-01T11:19:22.285Z',
    updated_at: '2021-10-01T11:27:12.554Z',
  },
  {
    id: 4,
    Nazev: 'O Mariánce 1',
    Text:
      '<p>Na začátku byla maminka, která šla za svým snem. Dopřát svým dětem školku bez zdí a plotů, na lukách a v&nbsp;lesích, s&nbsp;otevřenými smysly i srdcem. A tak vznikl v&nbsp;roce 2012 v Líšni Dětský lesní klub Mariánka jako jeden z&nbsp;prvních svého druhu v&nbsp;České republice. Stejně tak byl i mezi prvními lesními školkami, které věřily v&nbsp;kvalitu svého vzdělávání a razily cestu k&nbsp;uznání státem. To se jim také podařilo a od školního roku 2017/18 je Lesní mateřská škola Mariánka zapsána v rejstříku MŠMT. Můžeme tak poskytovat plnohodnotné předškolní vzdělávání, předškoláci se nemusí loučit na poslední rok s&nbsp;kamarády, podporu dostanou i děti se speciálními potřebami.</p><p>Máme radost, že do společenství školky patří neodmyslitelně i rodiče. Mají možnost zapojit se do příprav společných slavností, budování zázemí školky a mnohdy se stávají našimi blízkými přáteli. Snažíme se, aby Mariánka byla příjemným místem, kde se každý, dítě, rodič i pedagog, cítí vítaný, přijímaný a respektovaný.&nbsp;</p><p>Zdravé sebevědomí, soucit a úcta k ostatním lidem a pokorný vztah k přírodě, to jsou nejvzácnější dary, které bychom chtěli dát našim dětem na cestu životem i v dalších letech.</p><p><i>Chcete-li sledovat, jak to u nás žije, přidejte si nás na </i><a href="https://www.facebook.com/lmsMarianka"><i>Facebooku</i></a><i>.</i></p><p>Máte-li zájem o docházku do Mariánky, vyplňte nám prosím <a href="https://docs.google.com/forms/d/e/1FAIpQLScRORHdJQFHma37zTvFKGRQOfPY9FKERCnOsRAHn1tLsDvjfw/viewform?usp=sf_link">Nezávazný dotazník</a> a my se vám ozveme.</p><p>Zřizovatelem LMŠ Mariánka je spolek <a href="https://www.lesnikavyl.cz/">Kavyl</a> z.s.&nbsp;</p>',
    created_at: '2021-01-18T19:13:07.292Z',
    updated_at: '2022-02-16T09:41:39.770Z',
  },
  {
    id: 9,
    Nazev: 'Ceník',
    Text:
      '<p>Za dítě umístěné v naší lesní mateřské škole lze za kalendářní rok uplatnit slevu na dani. Za kalendářní rok 2022 je to až 16 200 Kč. Tento odpočet je vyřizován individuálně&nbsp; v rámci daňového přiznání.</p><h3><strong>Celodenní docházka na školní rok 2022-23</strong></h3><figure class="table"><table><thead><tr><th>Model docházky</th><th>Cena za měsíc (v Kč)</th><th>Cena za měsíc po odpočtu slevy na dani 16 200 Kč/rok</th></tr></thead><tbody><tr><td>Celotýdenní</td><td>7 500</td><td>5 880</td></tr><tr><td>Třídenní</td><td>5 600</td><td>3 980</td></tr><tr><td>Dvoudenní</td><td>4 100</td><td>2 480</td></tr></tbody></table></figure><p>V ceně není zahrnuto stravné.</p><p><strong>Nahrazování nemocí</strong><br>Řádná omluva daného dne docházky je do 8 hodin ráno&nbsp;do docházkového systému školky.&nbsp;Náhrada je evidována v docházkovém systému školky.<br>Náhrada je možná po domluvě se zástupkyní jakýkoliv jiný den v týdnu.<br>Není možné odhlásit dítě z pravidelné docházky a nahrazovat si pouze nemoci. Náhrady je možné uplatnit pouze do konce stávajícího školního roku.</p><h3><strong>Stravování</strong></h3><p>Obědy pro děti dovážíme ze Školní jídelny Novolíšeňská. Cena dotované dětské porce je 58 Kč včetně dovozu a není zahrnuta ve školkovném.&nbsp;<br>Každý rodič má přístup do docházkového systému školky a oběd lze odhlásit do 13:00&nbsp;předchozího dne.<br>Svačinky&nbsp;odebíráme ze Školní jídelny Novolíšeňská.</p>',
    created_at: '2021-01-18T19:15:28.859Z',
    updated_at: '2022-04-07T07:41:29.037Z',
  },
  {
    id: 2,
    Nazev: 'Kontakt2',
    Text:
      '<h3>Lesní mateřská škola Mariánka</h3><ul><li>školská právnická osoba</li><li>Sídlo: Hostěnická 626, 664 07 Pozořice</li><li>Provozovna: ul. Samoty, 628 00 Brno-Líšeň,<br>GPS 49.2155161N, 16.6988514E</li><li>IČ: 06 107 591</li><li>ID datové schránky: 6h4qvbm</li><li>č. účtu: 2802166482/2010 (Fio banka)</li><li>info@lesnimarianka.cz</li><li><a href="https://www.facebook.com/lmsMarianka">facebook LMŠ Mariánka</a></li></ul><h3>Pro rodiče</h3><p>Mgr. Klára Taufarová<br>koordinator@lesnimarianka.cz&nbsp;<br>604 536 796</p><h3>Ředitelka</h3><p>Mgr. Klára Krchňavá<br>klara.krchnava@lesnimarianka.cz&nbsp;<br>777 145 343</p><h3>Zřizovatel</h3><ul><li>Kavyl z.s.</li><li>Sídlo: Hostěnická 626, 664 07 Pozořice</li><li>IČ: 229 09 320</li><li><a href="http://localhost:3000/www.lesnikavyl.cz">lesnikavyl.cz</a></li></ul><h3>Pracovní příležitosti</h3><p>Máte-li zájem o spolupráci nebo stáž, kontaktujte ředitelku LMŠ Mariánka.</p>',
    created_at: '2021-01-02T19:18:37.290Z',
    updated_at: '2022-06-16T12:03:13.658Z',
  },
  {
    id: 14,
    Nazev: 'Dokumenty',
    Text:
      '<p><strong>Harmonogram školního roku LMŠ Mariánka</strong><br><strong>2022-23</strong><br>1/9 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;začátek školního roku<br>28/9 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;státní svátek – zavřeno<br>28/10 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;státní svátek – zavřeno<br>17/11 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;státní svátek – zavřeno<br>23/12 – 1/1 &nbsp;vánoční prázdniny<br>7/4 – 10/4 &nbsp; &nbsp;Velikonoce – zavřeno<br>1/5 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; státní svátek – zavřeno<br>8/5 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; státní svátek – zavřeno<br>30/6 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; konec školního roku&nbsp;<br>1/7 – 31/8 &nbsp; &nbsp;prázdniny</p><p><a href="/files/eticky_kodex_lms.pdf">Etický kodex</a><br><a href="/files/ochrana_osobnich_udaju_LMS_Marianka.pdf">Ochrana osobních údajů</a><br><a href="/files/kriteria_prijeti_2022.pdf">Podmínky pro podání žádosti o přijetí</a><br><a href="/files/pravidla_stiznosti_lms_marianka.pdf">Pravidla stížností</a><br><a href="/files/provozni_rad_lms_marianka_2019-09.pdf">Provozní řád</a><br><a href="/files/skolni_rad_lms_marianka_2019-04.pdf">Školní řád</a><br><a href="/files/svp_lms_marianka_2017_revize.pdf">Školní vzdělávací program</a></p><h2>Výroční zprávy</h2><ul><li><a href="/files/marianka_vz2017.pdf">Výroční zpráva o činnosti 2017/18</a></li><li><a href="/files/vz_hosp_2018.pdf">Výroční zpráva o hospodaření 2018</a></li><li><a href="/files/MARIANKA_VZ2019_preview.pdf">Výroční zpráva o činnosti 2018/19</a></li><li><a href="/files/vz_hosp_2019.pdf">Výroční zpráva o hospodaření 2019</a></li><li><a href="/files/MARIANKA_VZ2020_web.pdf">Výroční zpráva o činnosti 2019/20</a></li><li><a href="/files/vz_hosp_2020.pdf">Výroční zpráva o &nbsp;hospodaření 2020</a></li><li><a href="/files/MARIANKA_VZ2021.pdf">Výroční zpráva o činnosti 2020/21</a></li><li><a href="/files/vz_hosp_2021.pdf">Výroční zpráva o hospodaření 2020/21</a></li></ul><h3>Zápis</h3><ul><li><a href="/files/zadost_o_prijeti.pdf">Žádost o přijetí</a></li><li><a href="/files/evidencni_list.pdf">Evidenční list</a></li><li><a href="/files/dotaznik.pdf">Dotazník</a></li><li><a href="/files/oznameni-iv.pdf">Oznámení o individuálním vzdělávání</a></li></ul>',
    created_at: '2021-01-18T19:22:26.126Z',
    updated_at: '2022-10-31T14:20:57.648Z',
  },
  {
    id: 25,
    Nazev: 'Nabídka práce',
    Text:
      '<p>Máte-li zájem o spolupráci či stáž v LMŠ Mariánka, kontaktujte zástupkyni školy Kláru Taufarovou <i>koordinator@lesnimarianka.cz.</i></p><p><strong>Aktuálně</strong></p><p>Rádi do našeho týmu přijmeme kolegu/kolegyni na zkrácený úvazek. Podrobnosti <a href="https://lesnimarianka.cz/aktualita/34">zde</a>. V případě zájmu pošlete životopis na výše uvedený e-mail.</p>',
    created_at: '2022-07-22T12:07:30.796Z',
    updated_at: '2022-09-09T09:34:09.078Z',
  },
  {
    id: 12,
    Nazev: 'Tábory',
    Text:
      '<p>Letní příměstské tábory spolku Kavyl jsou pro děti ve věku 3,5–7 let, které ještě nechodí do školy. Vybrané tábory jsou i pro školní děti (u termínu je uvedený věk). Jsou-li u jednoho termínu a místa uvedeny dva tábory, znamená to, že organizujeme dvě skupiny (předškolní a školní) se samostatným programem, tak abyste mohli přihlásit najednou sourozence různého věku.</p><p>Tábory se konají v Líšni v zázemí Mariánky a v okolních lesích, druhým zázemím je <a href="https://www.stromik.cz/kontakt">lesní školka Stromík</a> v Pozořicích. Provozní doba tábora je vždy od pondělí do pátku od 8 do 16 h.</p><h3>Tábory 2023</h3><p><i>Příměstské tábory se budou konat v následujících termínech. <br/><br/> Brno-Líšeň (Mariánka)<br/> 10. - 14. 7. (3,5 – 7 let) Kouzelný les a jeho obyvatelé<br/> 17. - 21. 7. (5 – 8 let) Bylo, nebylo a co bude dál? <br/> 21. - 25. 8. (3,5 – 7 let) Dobrodružství v Čarolese<br/><br/>Pozořice (Stromík) <br/>10. - 14. 7. (1. – 3. třída) Hmyzí detektivové<br/>24. - 28. 7. (3,5 – 7 let a 7–10 let) Indiánskou stezkou<br/> 7. - 11. 8. (5 – 10 let) Mauglího dobrodružství - obsazeno<br/>14. - 18. 8. (3,5 – 7 let) Byla jednou jedna nota<br/> 21. - 25. 8. (3,5 – 7 let) Kouzelný les<br/><br/>Cena tábora je 2 500 Kč.<br/><br/>Přihlašovat můžete děti prostřednictvím <a href="https://forms.gle/raR2sCa3uFJmLZJR6">ONLINE PŘIHLÁŠKY</a>.<br/><br/>Zajímají-li vás podrobněji jednotlivá témata táborů, podívejte se na <a href="https://www.lesnikavyl.cz/files/tabory_anotace_2023.png">anotace</a>.<br/><br/>Těšíme se v létě na viděnou!</i>',
    created_at: '2021-01-18T19:16:22.269Z',
    updated_at: '2022-09-16T08:27:15.959Z',
  },
];
